### ISSUE TITLE
Coyote Organization, Roles & Responsibilities

### ISSUE THREAD

**Issue by subelsky** [coyote-team/coyote#111]
@TobeyeboT @susanchun @alavatelliMCA this week I am planning to tackle adding organizations, roles, & responsibilities to Coyote. Would love to get your feedback on this design for Coyote Roles that I have been hashing out w/ @sinabahram:

**Organization**: Represents the entity that originates or "owns" Coyote data. MCA itself would be represented as an Organization, and I assume the other museums participating in the scavenger hunt would be separate Organizations. 

* An Organization has a name, URL, and logo

* An Organization can choose to restrict the visibility of its content (exact details TBD, just need to make sure organizations can keep their data private from other organizations if they want)

**Roles and Responsibilities** (in descending order of power; higher level roles inherit the responsibilities of lower level roles):

* "Super Admin": able to mint new admin users for an Organization. This subsumes issue #97 and would address issue part of issue #89.

* Admin: able to mint new editor & author users; also would have access to Organization settings

* Editor: able to modify, approve, and disapprove all organizational content

* Author: Able to write new descriptions, able to upload new images [addresses issue #88], able to edit their own descriptions, able to edit their own images.

* Viewer: can read all of an organization's content

**Auditing & Deleting**

In general we won't deleting anything that affects auditing. Users, images, and descriptions could all be marked `inactive` or `deleted`, but the records would still remain in the database.

**Comment by sinabahram** [comment]
Responding to this specific part:

“I assume the other museums participating in the scavenger hunt would be separate Organizations.”

 

That is not exactly correct. As we discussed on last week’s call, we’re thinking of making a “Scavenger Hunt” organization and lumping everyone into there for each participating organizations’ users. The reason for this is ease of implementation for now, unless if there is a better way?

**Comment by subelsky** [comment]
That sounds good - since are following the model of github organizations, it would be possible for one user to play a role in different organizations.

This does make me want to press a little harder though: is Organization the right construct here? Or do we mean something like "Project"? In other words, are we likely to be thinking more in terms of institutions or more in terms of specific description efforts?

**Comment by sinabahram** [comment]
Almost always in terms of Organization and not in project, though Projects is a concept I’d love to explore far far down the road.

**Comment by susanchun** [comment]
Agree that Organization is the essential construct and that Project (such as in "Scavenger Hunt Project" is an outlier as we've imagined it here. The key reason to keep Org as an overarching concept is to not have to build and manage teams/roles (and assets) for multiple projects within an org.

**Comment by subelsky** [comment]
OK, I feel like I have enough to go on here. I'll start by making Organization, and users being members of multiple organizations.

**Comment by subelsky** [comment]
How many Organizations would a typical Coyote instance be running? Can any user create a new organization? (Github model)

**Comment by sinabahram** [comment]
Yes to any user creating an organization, but I don’t understand the point about an instance of Coyote. I thought we agreed on a centralized, if not distributed, aspect to this system, so would the answer be N, where N is defined by cloud-based resources?

**Comment by subelsky** [comment]
@sinabahram I'm imagining a scenario where some institutions use a centralized / multi-tenant instance of Coyote, hosted on a cloud platform like Heroku. Other / larger institutions could run their own instance on a different platform (or a server in their data center).

It would be more efficient, for sure, if all Coyote data was stored in one place and one system was serving all institutions. Let me know if you want to kick that idea around...

**Comment by sinabahram** [comment]
Yes, would love to discuss Coyote federation.

**Comment by subelsky** [comment]
Assumptions I have been making (not too late too change if you disagree):

1) Anyone can create an Organization (per the "Github model")

2) Organization adding/changing is accessed from the navigation menu in the upper right hand corner (vs adding more to the primary navigation menu bar at the top of page). Presumably this would eventually grow into a `Settings` page that includes other stuff besides Organizations.

3) We will need to scope the Dashboard/home page by Organization (also how Github handles it - if you are signed-in to Github, you can look in the upper left hand corner of the page and see a drop down that lets you change what you see for your dashboard).

Having Orgs will also mean breaking out `Role` into a separate database model. Because I can be a `superadmin` of one organization, but only an `author` of another.

**Comment by sinabahram** [comment]
closing this as it's concerns are split across various other issues or handled by now.
