### ISSUE TITLE
Propose change to concept of Status

### ISSUE THREAD

**Issue by subelsky** [coyote-team/coyote#112]
@TobeyeboT @susanchun @alavatelliMCA @sinabahram I would like to propose a change in the way Coyote handles description status. 

**Background**

Right now `Status` is managed as a user-created entity in the database, so every different installation of Coyote would end up using its own internal way of representing different statuses

This makes the code a lot more complex to write and maintain, because every time we handle status (such as when filtering a list of descriptions, or deciding which description to render) we have to try and understand how a particular Coyote instance maps the concept of Status. 

**Proposed Solution**

It would be much simpler to treat status as a column on the images table, with an enumerable type that is standard across all Coyote installations. We would start off with these standard statuses:

* `:ready_to_review`
* `:approved`
* `:not_approved`

Are there other statuses you can imagine? This can later be used to grow a much more complicated scheme that would use a state machine to spell out all the possible states a description could be in.

**Comment by sinabahram** [comment]
Shall we add “Deleted” to this list?

**Comment by alavatelliMCA** [comment]
I have rather confusing notes from a June 15 phone call:
Approval: Unapproved, Approved, Rejected (as it is), Approved unpublished
Publish state: Published, Unpublished, Deleted/Archived (need to build)

I think it depends if publish state and approval state are one or two fields, my notes imply we were considering two fields.

**Comment by sinabahram** [comment]
I think that by decoupling the idea of publishing from the linear flow of status, we can both simplify and strengthen the system. This is important from my perspective.

 

So, I propose that publishing get its own states, and they absolutely can be linked to the status of a description, but maybe not flattened into the same structure.

 

For example, this would allow the publishing of an unapproved description. I know that’s something MCA would never do, but other organizations, imagine one experimenting with crowdsourcing may very well do that, and it’s not our job to dictate the flow anyways.

 

Thoughts?

**Comment by subelsky** [comment]
Two fields make sense. 

Descriptions have an approval state: 

* A description can be Unapproved [new, unreviewed]
* Approved
* Rejected (needs to be edited, becomes "Unapproved" when author saves changes]

Descriptions have a Publish state:

* Published [live, accessible to public]
* Unpublished
* Archived [no longer relevant, will not show up in searches unless you explicitly specify]

**Comment by susanchun** [comment]
Just confirming, though, that the publish state is specific to context (MCA website, scavenger hunt, Artstor), right?

**Comment by subelsky** [comment]
@susanchun oh so a given description could be published in one context, but unpublished in another? In that case I would create a whole new `Publication` model representing the relationship between a description and a context.

**Comment by susanchun** [comment]
Yes, absolutely.

Related issue: some contexts will allow the publication of more than one description, while others will restrict publication to ONLY one. In our discussions, we've talked about how to order/mark multiple approved descriptions so that a call will return the correct one(s), and I just want to make sure that this is on your radar.

**Comment by subelsky** [comment]
OK, getting more sophisticated. Cool. How does this sound? 

A Context has a publishing strategy specifying how many descriptions to present for a given image. They could be: `First`, `First 3`, `All`.

A Context has a publish priority specifying how to sort the list of potential descriptions. I have less of a handle on what they could be but I imagine a rule like "first look for a description with Metum X, then fallback to Metum Y". Or "only publish a description if it is Metum X"

**Comment by subelsky** [comment]
btw I won't change this until we get to a part of the code that touches status. I just want to make sure the design to aim for

**Comment by subelsky** [comment]
@susanchun can you write a couple of examples of what a  `Context` would be?

**Comment by sinabahram** [comment]
I like this idea of a publishing strategy very much.

**Comment by susanchun** [comment]
Context examples:
MCA Website
Coyote.pics site
Scavenger Hunt

**Comment by sinabahram** [comment]
None of these are contexts.

 

Contexts are Web, Exhibitions, Poetry, Digital Interactive, Mobile, Audio Tour (this one is debateable, but I can argue it either way), etc.

 

Contexts should not map to anything specific to a particular organization, etc.

 

Does that help?

**Comment by subelsky** [comment]
So `Context` represents the situation in which a subject is being considered, and a Context has a strategy that influences which description(s) are presented

**Comment by sinabahram** [comment]
Yes

**Comment by susanchun** [comment]
Okay, these ideas seem to conflict. I *do* think Context is specific to an organization or project, if it isn't, there's no way that it can have a strategy influencing which description(s) are presented, since that's a matter at the publication level. And the whole purpose of having Context is to provide guidance to make description meaningful. General Contexts such as "Exhibition" aren't that useful here.

**Comment by subelsky** [comment]
Well couldn't we say an `Organization` has one or more `Contexts`? So `Context` would thus represent a set of `Images` along with rules for how to represent members of that set, using whatever `Descriptions` are associated with each image. Each `Organization` could then use `Context` to mean what they want

(Would love to get in front of a whiteboard to iron all of this out)

**Comment by sinabahram** [comment]
Yes, that’s exactly correct.

 

Contexts can be organization-specific, whereas metums tend to have more global applicability, though Organizations still must be able to add one, such as “Poetic”.

**Comment by subelsky** [comment]
see 684836d6f6ec0b30075f2f2f3aed6a228e0f89c1, starting to eliminate the concept of user-configurable status. With Resources & Representations, we'll switch to using an enumerated type that reflects the current contents of the `statuses` table:

* Ready to review
* Approved
* Not approved
