### ISSUE TITLE
Propose change to concept of Metum

### ISSUE THREAD

**Issue by subelsky** [coyote-team/coyote#113]
Similar to #112. Does `Metum` need to be user-configurable, or can we model that as application code? The [two definitions we supply](https://github.com/coyote-team/coyote/blob/master/lib/tasks/coyote.rake#L27-L29) in the new setup procedure seem like they would be broadly applicable.

**Comment by susanchun** [comment]
I think that it needs to be user configurable (perhaps a function limited to admins?). We've talked about "Poetry" as a metum, as an example of a non-standard kind of description that we might experiment with. Question: where are we handling languages, is "Alt, Spanish" a metum or is internationalization handled elsewhere?

**Comment by subelsky** [comment]
my understanding is the Metum would be `Alt`, and the language would be a property of the description.

**Comment by sinabahram** [comment]
I agree with that. Metum is alt, and language is property of the description, and the “type” would be plain/text or text/json, audio/mp3, etc.

 

As for poetry, I claim we should phrase that as a context, much like Web, or Digital Interactive, or Mobile, or so on.

 

This way, we can  have alt poetry, long description poetry, etc.

**Comment by susanchun** [comment]
I agree about type and language being a property of description. However, I disagree about poetry being a context, since it doesn't seem to me parallel to the other things, which are publishing platforms or end points. Maybe let it go at this point, since nobody is writing any poetry?

**Comment by sinabahram** [comment]
This is a fair point. It bothered me a little bit when I typed it, but I couldn’t place my finger on it. Poetry is a metum, not a context, and thanks for pushing back on that one.

 

 

Making that change, Susan are we fully agreed, though?

**Comment by frenchfrigateshoals** [comment]
Yes, thanks everyone!

**Comment by subelsky** [comment]
OK so what are other examples of possible `Metum` values? Does `Alt` and `Long` cover most cases, or is every installation of Coyote likely to use custom values? 

It's easier to make Metum standard (like we're talking about doing with Status) but obviously want to make the system as flexible as it needs to be

**Comment by sinabahram** [comment]
Alt

Long

Poetry

 

And I’m strongly considering changing alt to short, so that we separate it from the baggage of that word associated with the web. Just like how long doesn’t map to longdesc on the web, short need not map to alt, though it often does, of course.

 

so, our list so far is:

 

short

long

poetry

 

we could do custom1 and custom2, but it’s not like I forsee 10 possible values here.

 

MCA folks, ideas?

**Comment by susanchun** [comment]
I'm very much in favor of changing alt to short. And yes, that's our list so far. I don't see a lot of additional things coming in, though I could envision other institutions having variations having to do with (for example) specific character limitations or requirements based on Context that aren't currently specifically expressed in the metums. But that, I think, is a complication for another day.

Come to think of it, though, we at one point talked about being able to store recordings of these descriptions. How would we relate them, and where would they live? This is something for which we don't have an immediate need, but which I see as a strong potential utility.

**Comment by subelsky** [comment]
`short` is the new `alt`, for sure. I'm surprised by "poetry" though. If I understand the way you're using "poetry", could I suggest the term `poetic` instead? What about `philosophical`, `artful`, `critical` [e.g. curator or art critic's perspective], `technical` [what an artist or a theorist would say]?

Is it correct to say "A `Description` has one Metum. All Coyote requests are associated with a `Context`.  Coyote checks `Metum` to decide which `Description(s)` to present for a given image based on the rules set by the request's  `Context`.

@susanchun I talked with @sinabahram about other kinds of descriptions. We were planning to make `Description` represent something more general than just a textual description. Descriptions would have a `content_type` such as `text/plain`, `audio/mp3`, `audio/wav`, etc.

**Comment by susanchun** [comment]
I'll buy poetic instead of poetry, sure. And I think that the definition above is good. 

Re: description having broad meaning that then has a content type: this makes sense. However, because I can have many descriptions (short 1/text, long 1/mp3, long 2/mp3) associated with the same object, I'd want to be able to create an association between a text description and the mp3 or wav file. Does that work?

**Comment by alavatelliMCA** [comment]
To further confirm Mike's definition, I want to outline what I understand this means for our current project–

If Scavenger Hunt is an `organization` (group) and this project demands a specific style of description, we would still need to use `metum` for distinguishing a special mode of description, so a new `metum` would be created by Admin called something like 'clue' that would only be used by the Scavenger Hunt `organization`. So we would need `metum` to not just be controllable by Admin but also be either global (`short` and `long`) or `organization` (project)-specific, if it's only being used for the one `context` and `organization`. Am I following correctly?

**Comment by sinabahram** [comment]
Yes, that’s correct. This is also a beautiful argument for not making metum hard-coded.

**Comment by subelsky** [comment]
@alavatelliMCA makes total sense. `clue` is a great example of needing to extend `Metum` for particular cases. So we can keep `Metum` as-is unless there's any other concerns?
