### ISSUE TITLE
Restrict who can create/edit/delete Groups

### ISSUE THREAD

**Issue by subelsky** [coyote-team/coyote#116]
Right now Groups (soon to be called "Contexts") don't have any access controls. Which Roles (from #111) should be allowed to read/write/edit/delete a Group/Context? /cc @sinabahram

**Comment by susanchun** [comment]
From my seat, Admins and Super Admins only should be allowed to add/edit/delete Contexts. That's based on the way that we use Coyote at the MCA.

**Comment by sinabahram** [comment]
I agree with Susan on the proposed roles that will have context creation capabilities.

**Comment by sinabahram** [comment]
Just want to echo the above. @flipsasser  can you confirm this is true, and if so, close this out?

**Comment by flipsasser** [comment]
It is the case that only admins and super admins can create resource groups or meta. These are the two features which have largely replaced "context"
