### ISSUE TITLE
Accessing 'Descriptions' from navbar throws a type error in development

### ISSUE THREAD

**Issue by somedayrainbows** [coyote-team/coyote#117]
To reproduce, go to root, then click on 'Descriptions' in the navbar. 
(or just go here: http://localhost:3000/descriptions)

![screen shot 2017-08-02 at 12 48 02 am](https://user-images.githubusercontent.com/16053570/28861055-60f01798-771c-11e7-9d0f-7c102f6efb00.png)

**Comment by subelsky** [comment]
@somedayrainbows That's interesting, I would have thought `Haml` would take care of that here. However, since Haml uses [Ruby Interpolation](http://haml.info/docs/yardoc/file.REFERENCE.html#ruby-interpolation-) this is easy to fix, without having to use quotation marks. Can you fix?

**Comment by somedayrainbows** [comment]
Yes, I'll fix. Thank you!
