### ISSUE TITLE
Link from Coyote entry to the MCA context

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#12]
Link from Coyote entry to the MCA context

**Comment by seeReadCode** [comment]
I need to check if this info is already in the JSON but most likely there will be a request to Tomáš

**Comment by seeReadCode** [comment]
Info was not in JSON.  Email sent.

**Comment by seeReadCode** [comment]
Pinged Tomas again.

**Comment by seeReadCode** [comment]
Pinged again.
