### ISSUE TITLE
User login and user signup broken

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#120]
User sign up broken, so is user login (assuming MCA existing users were migrated)

Attempted login with alavatelli@mcachicago.org
Attempted account creation 
Thursday AM (just before writing this issue)

**Comment by sinabahram** [comment]
This is confirmed and reproduceable over here.

 

Steps to reproduce:

 

I went to sign up, used an email address that was not known to the system before, filled out all fields correctly, and then received an internal 500 error from the server on the page I was redirected to after form post.

**Comment by subelsky** [comment]
@alavatelliMCA @sinabahram so far I can't reproduce this. I changed @alavatelliMCA's password and tried signing-in with her email, to no avail. So you'll need to [reset your password](http://live.coyote.pics/users/password/new).

If it's still happening, I also setup Rollbar again, so I should be able to capture the details next time it happens. In the meantime will leave this issue open till we're sure it's no longer occurring.

**Comment by subelsky** [comment]
PS it may be related to the the jquery magic going on in the signup page. I'm overhauling / simplifying those pages as part of #111 so it may not be worth digging much more deeply here

**Comment by sinabahram** [comment]
This advice is not able to be followed. The forgot password page results in an http 500. Just tried it.

**Comment by sinabahram** [comment]
In addition, please note that the sign up form results in an http 500 still.

 

I just verified that as well.

 

 

President, Prime Access Consulting, Inc.

Twitter: @SinaBahram

Company Website: https://www.pac.bz

Personal Website: https://www.sinabahram.com

Blog: https://blog.SinaBahram.com

 

From: Sina Bahram [mailto:sina@sinabahram.com] 
Sent: Monday, August 28, 2017 11:35 AM
To: 'coyote-team/coyote' <reply@reply.github.com>
Subject: RE: [coyote-team/coyote] User login and user signup broken (#120)

 

This advice is not able to be followed. The forgot password page results in an http 500. Just tried it.

**Comment by subelsky** [comment]
OK got it, the forgot password is happening to me also; I can still sign up though. This gives me some stuff in Rollbar to look at, stay tuned.

**Comment by subelsky** [comment]
OK this looks like a DB issue, having to do with primary keys on the users table. Very strange, have not seen this kind of bug in a rails app before, and it seems to only afflict production. It could be an artifact of the way I migrated the data (which would explain why it only affects production) , will dig further.

**Comment by subelsky** [comment]
I fixed the issue - it was a database problem as suspected. Password reset still not working but that will be handled in #121

**Comment by subelsky** [comment]
@alavatelliMCA @sinabahram I have tested the signup, login, and reset password tests thoroughly. Everything should be good to go. (also see ticket #121)
