### ISSUE TITLE
Lightbox does not enlarge image

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#127]
Lightbox image dimensions should fill much more of the browser window to provide an enlarged view, otherwise, this feature should simply be removed. Currently, the image is the same size as it appears on the resource page making the lightbox purposeless.

screenshot of resource page, https://staging.coyote.pics/resources/1 
![screen shot 2018-07-09 at 2 52 05 pm](https://user-images.githubusercontent.com/8040710/42472653-bb5a97a8-8387-11e8-8991-ae41dc7b1ee9.png)

screenshot of lightbox on the above resource page–
![screen shot 2018-07-09 at 2 52 12 pm](https://user-images.githubusercontent.com/8040710/42472682-d2952762-8387-11e8-825e-9483c6bb887a.png)

**Comment by flipsasser** [comment]
The image was already being displayed at its full size in the "view resource" context. Other design changes have fixed this.
