### ISSUE TITLE
Archive or delete users?

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#128]
We discussed a solution to this on the phone, but I cannot find it in my notes. The original ask was to archive users instead of deleting them. And most importantly what happens to user descriptions when we “delete” them? We don't ever want to lose description content.

**Comment by sinabahram** [comment]
I suggest we archive them, which is nothing more than setting “archive=’true’” on their user object. Then the members page will only show those users that are active. This way, nothing happens to their descriptions what-so-ever.

**Comment by flipsasser** [comment]
This was deployed awhile back as part of the redesign!

**Comment by alavatelliMCA** [comment]
I see no option to archive users.

**Comment by stacietaylorcima** [comment]
I see the option to archive users in the code, so I have a feeling this is another permissions issue. I’m curious to know what happened with permissions/ Pundit authorizations when we moved to new coyote? @sinabahram @flipsasser

**Comment by flipsasser** [comment]
I believe this is a mismatch between staff and non-staff permissions. @alavatelliMCA, are you looking at the "Members" link when you search for the archive functionality?

**Comment by flipsasser** [comment]
This has been merged into master
