### ISSUE TITLE
Description page audit section, certain columns too narrow

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#129]
I'm not sure that all fields need to be displayed in the audit log, though I do like having complete information in the audit log. Each entry may need two rows so that the description and notes columns can be wider for legibility.

Fields listed
USER | ACTION | TIME | TEXT | AUTHOR | CONTENT TYPE | LANGUAGE | STATUS | METUM | ENDPOINT | LICENSE | CONTENT URI | NOTES
https://staging.coyote.pics/resources/10618
![screencapture-staging-coyote-pics-representations-5938-2018-07-05-10_59_36](https://user-images.githubusercontent.com/8040710/42535294-9da88260-8454-11e8-941d-5c5890f64da0.png)

**Comment by stacietaylorcima** [comment]
**Question/suggestion:** What would you think about for the longer format fields (text, notes, etc) having a button that says "view" that when you click it, a modal pops up with the information? Let me know what you're thinking. I'm just trying to brainstorm ways we can keep this page clean and concise but still keep all the information at our fingertips. @alavatelliMCA @sinabahram

**Comment by sinabahram** [comment]
@alavatelliMCA should take the lead on this, but I hesitate to berry information any more in this interface. If anything, the usual usable concerns from Anna an others is around needing to go through too many steps to access something, so a modal may be heading in the wrong direction.

**Comment by alavatelliMCA** [comment]
Oops, I will close duplicate I just made. I think burying information is a bad Idea as well. How about scaling type down a little and abbreviating column headers? E.g. Lang for Language?

**Comment by flipsasser** [comment]
This was fixed and deployed in July
