### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#13]
Accessibility & Next Client: Testing. 
- [x] travis ci: test builds
- [x] code climate: code quality
- [x] coveralls: test coverage
- [x] check to see if feed updated on codeclimate
- [x] remove coveralls bc of test coverage in codeclimate?
- [x] improve code quality to 3.8
- [x] build passes? 
- [x] Update factories of models
- [x] Set testing priorities
- [x] create correct statuses in factory
- [x] create correct meta in factory
- [x] consider using [airborne](https://github.com/brooklynDev/airborne) for JSON tests
- [ ] JSON tests for critical API endpoints (mainly images.json)
  - [ ] GET images/canonical_id filter
  - [ ] GET images/status filter & images/1
  - [ ] GET images/status default & images/1
  - [ ] GET images/priority filter
  - [ ] GET images/pagination
  - [ ] POST images
  - [ ] PUT/PATCH images/1.json 
- [ ] decide how to integrate strategy tests
- [ ] https://github.com/Apipie/apipie-rails#examples-recording
- [ ] Controller tests for core actions
- [ ] controller test for PATCH to asset
- [ ] Model level tests http://everydayrails.com/2012/03/19/testing-series-rspec-models-factory-girl.html
- [ ] HTML view tests
  - [ ] Check if the valid asset lib is still working https://github.com/unboxed/be_valid_asset
  - [ ] Articulate and implement accessibility testing with Tenon 
- [ ] Set coverage range benchmarks
- [ ] Resolve code quality issues listed below
- [ ] Consider Codeclimate within guard https://github.com/metavida/guard-codeclimate
- [ ] Consider Gemnasium https://gemnasium.com/
- [ ] webmock should allow code climate messages from travis

**Comment by seeReadCode** [comment]
https://coveralls.io/ for code coverage

**Comment by seeReadCode** [comment]
Code climate issues

- [ ] https://codeclimate.com/github/coyote-team/coyote/app/controllers/assignments_controller.rb
- [ ] https://codeclimate.com/github/coyote-team/coyote/app/controllers/descriptions_controller.rb
- [ ] https://codeclimate.com/github/coyote-team/coyote/app/models/image.rb
- [ ] https://codeclimate.com/github/coyote-team/coyote/config/initializers/simple_form_bootstrap.rb
- [ ] https://codeclimate.com/github/coyote-team/coyote/db/schema.rb
- [ ] https://codeclimate.com/github/coyote-team/coyote/lib/coyote/strategies/mca.rb

**Comment by subelsky** [comment]
@alavatelliMCA I think I can help with some of the outstanding items here (seems like the easiest place for me to start helping). Lmk if there's a particular place I should start. Or if we could do a quick skype call to get oriented or save typing

**Comment by alavatelliMCA** [comment]
I think this is all resolved with New Coyote, no?
