### ISSUE TITLE
Admins can't edit Admins

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#130]
I should be able to remove or adjust fellow Admin's accounts or we need something above admin for organizational leads to be able to edit users. We have several people who are no longer staff with admin rights that I need to adjust or remove.

Screenshot showing no option to edit admin users
![screen shot 2018-07-09 at 2 35 50 pm](https://user-images.githubusercontent.com/8040710/42535652-8bd63036-8455-11e8-9e43-ef213997aec8.png)

**Comment by sinabahram** [comment]
I agree, but I think this has already been done. I remember working with Mike on this. let’s discuss on our next call and then figure out where the disconnect is.

 

In fact, I know this is true, but I see the problem. You are currently not an “owner” of the organization. That is why you can’t edit fellow admins, so this is a content, not functionality concern.

 

Let’s make you an owner and reevaluate, yes?

**Comment by alavatelliMCA** [comment]
Great, I'll log back in and check it out.
