### ISSUE TITLE
Ready to Review Queue visual treatment needs adjustment

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#131]
Objects in the dashboard Queue in other lists have a box that contains the entire block of elements, the image, caption, labels, and buttons. In the ready to review descriptions, there is a different treatment that makes it confusing as to the contents of each block. It should have a similar visual treatment to the other Queues, similar to old coyote.

new coyote
![screen shot 2018-07-09 at 2 32 42 pm](https://user-images.githubusercontent.com/8040710/42535693-ae54f1b0-8455-11e8-8709-e9e4d1163ddd.png)

current coyote
![screen shot 2018-07-10 at 3 29 16 pm](https://user-images.githubusercontent.com/8040710/42535807-0ae8ce24-8456-11e8-9152-950b10961242.png)

**Comment by stacietaylorcima** [comment]
Hi @alavatelliMCA! I wanted to get some clarification on this issue. I've updated the style of the Ready to Review queue to more closely match old Coyote per issue #164 (see image below). But, I think this issue may be hitting on some other issues with it that I don't fully understand (like maybe order of the elements or something). Can you take a look at the screenshot below and let me know what other changes you'd like to see! Thanks so much. :-) 
![ready to review updates](https://user-images.githubusercontent.com/25017973/45074385-24940c80-b098-11e8-94d9-f1f6089d0997.png)

**Comment by alavatelliMCA** [comment]
Hi Stacie, This looks fantastic. Thank you! 
I don't see any issues with the screenshot, is there something that I might be missing that I should be looking for?

**Comment by stacietaylorcima** [comment]
Excellent! Glad to hear it's what you were looking for. I was only asking for clarification because I wasn't sure if there were things you wanted to be rearranged (example: moving the "by author" under the tags) or something. Things aren't in the exact same order as before, so just let me know if there are any other tweaks. If not, I just pushed fixes for this to staging and I can close the issue for now! @alavatelliMCA

**Comment by alavatelliMCA** [comment]
I actually think it looks better the way you have it. Let’s push and close it out!
Thanks.


Anna Chiaretta Lavatelli
Director of Digital Media

Museum of Contemporary Art Chicago
220 E Chicago Ave
Chicago, IL 60611
alavatelli@mcachicago.org<mailto:alavatelli@mcachicago.org>
312-397-4047<tel:312-397-4047>
mcachicago.org<http://www.mcachicago.org>
This message is for the designated recipient only and may contain privileged,
proprietary, or otherwise private information. If you have received it in error,
please notify the sender immediately and delete the original. Any other use of
the email by you is prohibited.
