### ISSUE TITLE
Home link and already signed in message is awkward

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#132]
So it would be more intuitive if once signed in that clicking on the Coyote eyes in the upper left that you would return to the dashboard instead of the login page. (This is how current coyote works) 

Because of the instinct to click in the upper left to return to the dashboard, one gets to the login page. After clicking login, you are sent to the dashboard but a blue box stating that you are already logged in in the upper left which does not go away until clicking away from the dashboard.

![screen shot 2018-07-09 at 2 34 01 pm](https://user-images.githubusercontent.com/8040710/42582990-dc5e7cb6-84f5-11e8-8952-4cf427643ea7.png)

![screen shot 2018-07-09 at 2 31 58 pm](https://user-images.githubusercontent.com/8040710/42583050-f081be06-84f5-11e8-89d6-2fa869ed16ee.png)

**Comment by alavatelliMCA** [comment]
Same issue as #160

**Comment by stacietaylorcima** [comment]
Closing because of duplicate. Will complete this today and close the other issue as well.
