### ISSUE TITLE
Occasional spacing issues on bottom edge of box on Queue items

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#133]
Some boxes have the incorrect spacing on outer edge. This is a low priority issue.

<img width="1222" alt="screen shot 2018-07-05 at 9 22 40 am" src="https://user-images.githubusercontent.com/8040710/42583411-818cf938-84f6-11e8-9fdb-f48e5f110081.png">

**Comment by flipsasser** [comment]
This has been fixed for a long time! Please re-open if there's a regression. Sorry for not closing this sooner.
