### ISSUE TITLE
Accept user's answers by comparing to resource_id using fuzzy match

### ISSUE THREAD

**Issue by stacietaylorcima** [coyote-team/coyote#139]
The "Enter object type" input on the new answer form was originally built as a type-ahead against all of the resources in Coyote under that organization to determine whether or not it's the right answer. We need to use a fuzzy matching gem to do some generous string matching. We'll need to at least lowercase everything, take out white space, and take out special characters. Then, if it ==  the right answer it's accepted. 

**View:**
- [ ] Remove the existing form and create a new simple form 
  - [ ] This form needs to send the user input to the `create` method in the `answers_controller` 

**Controller:**
- [ ] In the `create` method of the `answers_controller` the `@answer` needs to be lowercase, remove whitespace, remove special characters
- [ ] Then the controller needs to use some kind of fuzzy mathcing tool to match the `@answer` with the clue's :title. I need to do some digging to figure out which gem/tool to use for this and to figure out how to access the clue's title. 
- [ ] if the new `answer` matches the clue's title:
  - [ ] if game is over redirect to `finished_game_path`
  - [ ] else redirect to `correct_game_clue_answer_path`
- [ ] if `answer` does not match the clue's title: redirect to `incorrect_game_clue_answer_path`
  
**Other tasks:**
- [ ] Remove all of the typeahead/autocomplete code that was associated with this funtionality
- [ ] Style the new answer form

**Comment by stacietaylorcima** [comment]
My dev community has recommended [Searchkick](https://github.com/ankane/searchkick ), so I'll check it out. Let me know if any of you have used this or have feedback.

**Comment by sinabahram** [comment]
It occurs to me that we could replace the regular Coyote search with this, potentially as well?

 

I’m curious about the technical debt. It requires elastic search, etc., which is fine, but I just want to be cognizant of that.

 

It looks promising.

**Comment by stacietaylorcima** [comment]
**Feeback Request:** Ended up going with something much simpler than elasticsearch/searchkick. 

- Replaced the existing form and all typeahead/autocomplete with a more basic form to accept the user's input. 
- In the answers_controller, used similar_text gem in the create method. similar_tex offers .similar as a method to compare two strings and return a score (integer) of how well those strings match. I am comparing the @clue.resource.title with the player's input. 
- If they have a match score of more than 40, the answer is accepted. We can adjust this to be more lenient or strict based on what you all want. 

**Screen recording walk-through:** https://drive.google.com/file/d/1Jyy9RXVazNaJQ2EgYx5UzDe1ofODbtzt/view
