### ISSUE TITLE
Implement Metum Ordinality 

### ISSUE THREAD

**Issue by stacietaylorcima** [coyote-team/coyote#143]
Ordinality needs to exist at the metum level. So, if we have 10 long descriptions for a specific resource, what's the order of them? The user needs the ability to set the order of the metum when adding or editing a representation's metums. This order will be an integer that will default to 0. _(Note: this issue is at the Coyote level. Scavenger Hunt should simply use the same queries that are used in Coyote.)_ 

**Research:** 
* Find out how metums are coded in Coyote and make sure I understand that data model. 
* Find out what Postgres offers for sorting options on columns of database tables. If that exists, we might be able to implement this with very little modification to the code. 

**UI:** 
* On the representation edit view, we need an order selector
* On the resource show view, we need to add a column to the descriptions table that will display the order value

**Model:** 
* Add order field to the Metum model. These will be non-negative integers. 

**Controllers:** 
* Respect the metum order field in all the necessary queries.

**Comment by sinabahram** [comment]
Question: why will order be negative integers?

**Comment by stacietaylorcima** [comment]
@sinabahram That was supposed to say "non-negative". Sorry for the confusion! I've updated the issue.

**Comment by stacietaylorcima** [comment]
@sinabahram In the database, the order value can be any integer. But how many options should be presented to the user in the view? Should this be a drop-down selector or a numeric input field?

**Comment by sinabahram** [comment]
Can you just restrict it to be between 0 and 100 with 10 being default? My reasoning being that we may have a situation where folks wish to prioritize a list of things, and just make sure that a handful of items comes first, but don’t care about the rest. Defaulting everything to 10 instead of 0, offers this flexibility.

**Comment by stacietaylorcima** [comment]
@sinabahram 

**RE: default values** - I did some testing and I am thinking we should just let them default to `null`. In that case, they will still fall to the bottom of the list and it seems clean. 

<hr>

**Note:** I need to use `index` or some other word other than `order` for the column because it's protected. 

<hr>

**Updates & Revelations:** 
Just spent a bunch of time working through this and trying to wrap my head around it and realized, the `index` shouldn't be on the Metum level because there is only one record for each metum. So, if we set a column for `index` on the Meta table, we can only assign it one value instead of a value for each representation it is associated with. 

I believe the `index` column would actually need to be on the Representation level and then we could sort by `meta.title, representation.index` to get a list that would look like this: 

- Representation A, Metum: Long, Index: 1
- Representation B, Metum: Long, Index: 2
- Representation C, Metum: Long, Index: null
- Representation D, Metum: Short, Index: 1
- Representation E, Metum: Short, Index: 3
- Representation F, Metum: Short, Index: null
- Representation G, Metum: Short, Index: null

<hr>

Scope might look something like this: `scope :by_metum_title_with_index, -> { joins(:metum).order("meta.title, representation.index ASC") }`

**Comment by sinabahram** [comment]
This is true. Please proceed.

**Comment by stacietaylorcima** [comment]
Closing this issue and opening issues that are more specific based on our new plan. 

We are no longer "Implementing Metum Ordinality" as mentioned in the title of this issue. But are instead implementing resource and representation ordinality and scoping those objects by ordinality.
