### ISSUE TITLE
Error messages for when user attempts to "approve" more than one Scavenger Hunt: Clue or Answer

### ISSUE THREAD

**Issue by stacietaylorcima** [coyote-team/coyote#151]
For the Scavenger Hunt to work, the content managers must only apply the "approved" status to 1 Scavenger Hunt: Clue and 1 Scavenger Hunt: Answer on each resource. We need to add an error message that notifies/prevents the user from approving more than one.

**Comment by sinabahram** [comment]
Closing for now since this is scavenger hunt-related.
