### ISSUE TITLE
Visual change on status update (list-view)

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#155]
https://staging.coyote.pics/organizations/1/representations

When selecting the many "ready to review" and then attempting to bulk 
<img width="1436" alt="screen shot 2018-08-30 at 9 36 43 am" src="https://user-images.githubusercontent.com/8040710/44863827-d5874b00-ac43-11e8-89c3-6ac8a1f387cb.png">

**Comment by alavatelliMCA** [comment]
This bug is now blocking my ability to efficiently approve sample content. I will approve selected content manually if this is a complicated issue to solve.

**Comment by alavatelliMCA** [comment]
Hooray, it works. However a small bug (hopefully small).

When I selected bulk status change to approved there is no visual change. The screenshot below shows that there is a notification in the upper left that states "Status changed to 'Approved'" however there is no visual change until I click on descriptions again to reload, as shown in two screenshots below.
![screen shot 2018-09-06 at 3 17 51 pm](https://user-images.githubusercontent.com/8040710/45191954-77da9c00-b20b-11e8-9c2a-cd70c03c985f.png)

![screen shot 2018-09-06 at 3 18 05 pm](https://user-images.githubusercontent.com/8040710/45191953-77da9c00-b20b-11e8-9fc3-40b9831ae056.png)

**Comment by alavatelliMCA** [comment]
Related to #202

**Comment by stacietaylorcima** [comment]
I just tested and I think this is working now. Can you retest this and if it's not working, give me specific steps to recreate the bug. Thanks a million! @alavatelliMCA

**Comment by sinabahram** [comment]
@alavatelliMCA, friendly poke

**Comment by flipsasser** [comment]
I can confirm this is working as intended

**Comment by flipsasser** [comment]
I apologize for the unclear comment - the bug is fixed and it's working as was originally intended; I'm not saying that we intended to provide no visual clue as to a change in status
