### ISSUE TITLE
Content URI Description Field

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#156]
![screencapture-staging-coyote-pics-organizations-1-resources-new-2018-08-29-16_43_25](https://user-images.githubusercontent.com/8040710/44868630-015cfd80-ac51-11e8-9bf1-31d82f5a840c.png)

**Comment by sinabahram** [comment]
Sorry, there’s just a linked graphic, so I want to make sure I’m parsing this issue correctly. This is meant to capture the issue around having a description field in addition to the canonical URI field of a resource. is that right?

 

It says description or notes field, and that makes it feel like a description or notes for the resource, and I want to capture that point Susan made correctly.

**Comment by alavatelliMCA** [comment]
Ah, I may have misinterpreted. I think you were right I just transcribed it incorrectly in my notes–@susanchun was it a description of the URI or the resource?

Notes on this (which transcribes related elements of screenshot)

CREATING A NEW RESOURCE (labels and help text pasted below, needs edit to clarify)
 
NEW CANONICAL ID  (should be auto created, cross tabbing against existing IDs, hide from UI)
 
IDENTIFIER (clearly indicate that this is what creates URL)
This should be a unique string that does not change - used to identify the resource within Coyote. If blank, we will attempt to set one for you based on the title field.
 
SOURCE URI (this is reference, not canonical)
Identifies the canonical location of the resource, if available
 
HOST URIS (this is where it can be found, referenced, etc.)
Identifies the locations where the resource is normally hosted or viewed. Separate lines are considered separate URIs.
 
Add: DESCRIPTION field

**Comment by sinabahram** [comment]
Let’s please generate 2 more tickets for these. Let’s go through one by one:

 

This current ticket should be renamed to add “Content URI Description” field to Resource, full stop. That field is a text field meant to describe the content URI e.g. “map of where this object live” or “latitude and longitude of statue” or something … It’s not meant to describe the resource at all, but instead to simply describe the content URI field. that way we know what the URI means.

 

Then, can you, Anna, please make separate tickets for these?

 

1:

NEW CANONICAL ID (should be auto created, cross tabbing against existing IDs, hide from UI)

 

2: Text/Help Changes on Resource creation

IDENTIFIER (clearly indicate that this is what creates URL)
This should be a unique string that does not change - used to identify the resource within Coyote. If blank, we will attempt to set one for you based on the title field.

 

SOURCE URI (this is reference, not canonical)
Identifies the canonical location of the resource, if available

 

HOST URIS (this is where it can be found, referenced, etc.)
Identifies the locations where the resource is normally hosted or viewed. Separate lines are considered separate URIs.

**Comment by sinabahram** [comment]
This is no longer rellavent.
