### ISSUE TITLE
Cannot create a new organization

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#158]
I have no option to create a new organization.

![screen shot 2018-08-30 at 2 23 53 pm](https://user-images.githubusercontent.com/8040710/44874312-679d4c80-ac60-11e8-86fe-541f14e9cfea.png)

**Comment by sinabahram** [comment]
This is critical. To be clear, any user, what-so-ever, should be allowed to create an organization, regardless of permission level, as long as they are logged in, since they will then become the owner of the new organization.

 

Not sure how this got lost?

**Comment by stacietaylorcima** [comment]
This is totally critical! I've just submitted a pull request with a proposed fix. @sinabahram @alavatelliMCA
