### ISSUE TITLE
Text showing characters instead of visual styling for status

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#161]
Status is showing as "ready_to_review" on the description/representation page insteaded of formated with spaces or in label style–
![screencapture-staging-coyote-pics-representations-5966-2018-08-29-17_12_19](https://user-images.githubusercontent.com/8040710/44881746-54957700-ac76-11e8-9860-ca0a5ae91e9f.png)

Maybe not necessary, but it is preferred that status and metum show up in their label style in the audit log as shown here in old coyote:
![screen shot 2018-08-30 at 5 02 43 pm](https://user-images.githubusercontent.com/8040710/44881936-f6b55f00-ac76-11e8-9fe3-941b876b3d59.png)

**Comment by stacietaylorcima** [comment]
Totally agree with your note about the labels, @alavatelliMCA. It makes it way more readable. Fixed both of the things you mentioned! Keep me in the loop if you see other places that similar labels should be updated. I know this display appears frequently throughout Coyote, but I'm not familiar enough yet to know exactly where they should be.

This issue will be closed upon Pull request approval and successful `squash & merge`.
