### ISSUE TITLE
Resource type includes the _

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#162]
Resource type isn't styled shows as `still_image`

Thanks!
![screen shot 2018-08-30 at 6 29 19 pm](https://user-images.githubusercontent.com/8040710/44884754-e0150500-ac82-11e8-87e5-6bbd99dcfe34.png)

**Comment by stacietaylorcima** [comment]
Fixed! This issue will be closed upon Pull request approval and successful `squash & merge`.
