### ISSUE TITLE
Remove horizontal rules between statistics on dashboard

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#163]
Horizontal rules are distracting, these somehow got put in rather than the bar graphs shown in the design when the way the data was displayed changed. So let's lose the lines.

Potential phase 2 on the back burner, if the numbers in the dashboard are changed to a '# of #' format with fewer lines, add the thin bar graphs back.

**Comment by stacietaylorcima** [comment]
@alavatelliMCA Could you send me the design guide for this? I've got the Scavenger Hunt guide, but no guide for New Coyote. 

Is this what you mean when you say you want the horizontal rules removed? 
![no border](https://user-images.githubusercontent.com/25017973/44891716-bd401c00-ac95-11e8-9945-e87c4c4d35a2.png)

**Comment by alavatelliMCA** [comment]
Yes, this is it exactly. The horizontal rules came into play after the bar graphs were removed. Previously the dashboard had different statistics that were organized in a # of # fashion so a bar graph made sense. I am reviewing the dashboard with power users to ensure they are happy with this new approach to the stats. I will follow up if anything changes.


Anna Chiaretta Lavatelli
Director of Digital Media

Museum of Contemporary Art Chicago
220 E Chicago Ave
Chicago, IL 60611
alavatelli@mcachicago.org<mailto:alavatelli@mcachicago.org>
312-397-4047<tel:312-397-4047>
mcachicago.org<http://www.mcachicago.org>
This message is for the designated recipient only and may contain privileged,
proprietary, or otherwise private information. If you have received it in error,
please notify the sender immediately and delete the original. Any other use of
the email by you is prohibited.
