### ISSUE TITLE
Ready to Review Queue styling

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#164]
New Coyote styling is out of step with design docs for the "Ready to Review" Queue
![screen shot 2018-08-30 at 6 36 16 pm](https://user-images.githubusercontent.com/8040710/44884904-a09ae880-ac83-11e8-9759-d5088fe15198.png)

In the old Coyote interface shows styling where the resources, their captions, and all associated representations/descriptions are displayed with their labels inside of thin black ruled box (like other queues) with simple horizontal rules between descriptions, as shown in screenshot below.
![screen shot 2018-08-30 at 6 37 10 pm](https://user-images.githubusercontent.com/8040710/44884947-d9d35880-ac83-11e8-97ca-eeb2d2a4a242.png)

Feel free to break out into multiple issues as needed.

**Comment by stacietaylorcima** [comment]
Shoot me the design guide and I'll see what I can do to fix this! @alavatelliMCA  :+1:

**Comment by sinabahram** [comment]
There is a design refinements PDF in the docs folder in the repo

**Comment by alavatelliMCA** [comment]
Hi Stacie, it looks like you don't have an account on the old coyote: http://coyote.mcachicago.org

The queues are well designed there, and that is where the screenshot from above comes from with the rules around the whole resource and descriptions with horizontal rules between comes from. If you create an account I will make you an admin.

**Comment by stacietaylorcima** [comment]
Hi Anna! Before i go any further, I wanted to make sure I'm on the right track with this style update. It's a lot closer to the old version, but I kind of like the gray and think it provides nice seperation. What do you think? Can you take a look at this and let me know if it looks closer to how you want it? Also, can you let me know the specific tweaks that still remain. Thanks a million! :-) @alavatelliMCA 

![closer](https://user-images.githubusercontent.com/25017973/44999096-a63c4b00-af6f-11e8-9df9-aea89aa1962d.png)

**Comment by alavatelliMCA** [comment]
Hi Stacie, thank you, it's much closer! Although, I'm not so fond of the gray. But preference aside, the visual style dictates that everything be black and white so I would prefer a horizontal rule to divide each entry below the caption. 

Also, it seems like there is a spacing issue around the image. There should be a small amount of space between the rule and the image on all sides as it is in the other queue. So that the line acts as a container for the whole set of content, as shown in this screenshot–
![screen shot 2018-09-04 at 10 37 27 am](https://user-images.githubusercontent.com/8040710/45041692-90418f80-b02e-11e8-942d-abe1835b034e.png)

**Comment by alavatelliMCA** [comment]
I think everything else is looking spot on, thus far and that it's just this queue that we want to base off old Coyote. There were a few elements in new coyote introduced without any known reason on the MCA side, such as the treatment of these items on the dashboard. Feel free to point me to any other items that don't have a clear directive I am happy to clarify.
