### ISSUE TITLE
Roles and permissions

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#167]
I might just be blind, but I couldn't find the outline of the roles and their permissions in the documentation. This issue is to 1. pester you for these details and 2. add to the documentation

I see these roles and want to be sure I have a clear understanding of them:

Guest
Viewer
Author
Editor
Admin

Thanks!

**Comment by alavatelliMCA** [comment]
We are trying to get a few pages into the distributed authoring system, but it seems that permissions are no longer configured the way they were so I don't have a sense of how to ensure the roles are properly set up to accommodate users submitting updates directly to a page, and ensuring we get a notification.

Thanks!

**Comment by sinabahram** [comment]
Is this intended for Coyote?

**Comment by alavatelliMCA** [comment]
Oh god, sorry. I am rushing too much.
