### ISSUE TITLE
Resolve duplicate images? 

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#17]
This could possibly be resolved by ability to see context– #12

**Comment by seeReadCode** [comment]
We could also use https://github.com/westonplatter/phashion

**Comment by seeReadCode** [comment]
Do we still care about this? @sinabahram @alavatelliMCA

**Comment by sinabahram** [comment]
How much effort would it be to simply offer a manual ability to mark something as a duplicate? It is a necessary, but hardly sufficient, feature request to the one described in the ticket, so it gets us closer to the goal at hopefully a fraction of the implementation time, or so I am hoping?

**Comment by seeReadCode** [comment]
closing as its duped by #74
