### ISSUE TITLE
Help text Changes on Resource creation

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#175]
I'll work on these with SC, but feel free to take a pass on clarifying purpose of field.
Text/Help Changes on Resource creation

IDENTIFIER (clearly indicate that this is what creates URL)
This should be a unique string that does not change - used to identify the resource within Coyote. If blank, we will attempt to set one for you based on the title field.

SOURCE URI (this is reference, not canonical)
Identifies the canonical location of the resource, if available

HOST URIS (this is where it can be found, referenced, etc.)
Identifies the locations where the resource is normally hosted or viewed. Separate lines are considered separate URIs.

**Comment by flipsasser** [comment]
Did this forever ago; sorry for not updating the ticket!
