### ISSUE TITLE
Auto create Canonical ID

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#176]
NEW CANONICAL ID should be auto created, cross tabbing against existing IDs
This field should also be hidden from UI, but @sinabahram it should be viewable (and editable?) on the resource? Not sure where we left that part of it.

**Comment by alavatelliMCA** [comment]
Understood and confirmed.

**Comment by flipsasser** [comment]
This is done

**Comment by alavatelliMCA** [comment]
This is not working on the new organization I just made.

No ID auto fills, I had to enter one to create the ID on this resource -https://staging.coyote.pics/resources/20390

**Comment by flipsasser** [comment]
This is not to generate identifier; this is to generate canonical ID. Are you seeing issues with identifier or canonical id?

**Comment by sinabahram** [comment]
Closing this out. Cononical ID is not auto-generated, but rather provided by clients of the API. That's it's point.
