### ISSUE TITLE
Description should have a primary flag per metum per locale

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#18]
Longdesc default per website (Identify default approach?)
When multiple descriptions are approved for publish (can this happen?) which description is used on the site?

**Comment by seeReadCode** [comment]
I'm thinking we would just sub the default longdesc default into the JSON return but not show it on the Coyote UI or store it as a longdesc per image.

**Comment by seeReadCode** [comment]
What would an example longdesc default be, i.e for MCA?

**Comment by sinabahram** [comment]
I think we need to re-think default longdesc. Alt makes sense as “”.

**Comment by seeReadCode** [comment]
The default for both is currently "".  If we want to change this, let's discuss soon?

**Comment by seeReadCode** [comment]
We could eventually offer a `"primary": true`

**Comment by alavatelliMCA** [comment]
I defer to Sina on the appropriate method for implementation, but that sounds right to me.
