### ISSUE TITLE
Demo instance 

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#20]
- [x] Chris: README instructions for install adapted from Vagrant

**Comment by seeReadCode** [comment]
@sinabahram might you spin up an Ubuntu server on AWS for me to test out provisioning via chef?

Here's one HOWTO I'm considering:
https://gist.github.com/francois-blanchard/f9372f48c15ffade2c9c

Open to suggestions or providing a bash script and a README.

**Comment by seeReadCode** [comment]
Might concede on chef and move towards docker

**Comment by seeReadCode** [comment]
Punting on docker as well.  Updating README and then Sina will attempt install on demo.coyote.pics

**Comment by seeReadCode** [comment]
ready for you @sinabahram to try spinning up an instance

**Comment by seeReadCode** [comment]
@sinabahram ping

**Comment by sinabahram** [comment]
I think we can close this out now.
