### ISSUE TITLE
Events not showing in chron order in search

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#201]
This is a bit problematic, apparently, folks are searching for vernissage and not always seeing that this year's is happening. Funny because for me 2018 is showing up first, but I'm also not sure what search terms are being used.

![screen shot 2018-09-05 at 11 55 21 am](https://user-images.githubusercontent.com/8040710/45108610-b33d7380-b102-11e8-902f-e288722f727e.png)

**Comment by sinabahram** [comment]
sCould you explain this a bit further? Are you saying that the created_at timestamps were not maintained across the import?

**Comment by alavatelliMCA** [comment]
Oh my goodness, wrong github. Closing this reopening on mca website. So sorry. Chaos.
