### ISSUE TITLE
Store license per description

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#21]
- [x] store license per description
- [x]  [CC0](https://creativecommons.org/choose/zero/) default, options? 
- [x] form field on edit, display with on show
- [x] display in JSON

ref

- https://choosealicense.com/appendix/
- https://spdx.org/licenses/
- https://creativecommons.org/licenses/
- <https://github.com/kmewhort/creative_commons_rails>

**Comment by alavatelliMCA** [comment]
@sinabahram I added this verbatim from your notes, but I am actually not sure what it means, do you remember?

**Comment by seeReadCode** [comment]
I think this was an ask from MCA to associate rights info from the CMS with the image within the Coyote UI.

**Comment by sinabahram** [comment]
This was a request from you, actually, regarding associating permissions/rights info e.g. creative commons, do not reproduce/share, etc. etc.

**Comment by seeReadCode** [comment]
@alavatelliMCA so do we want to build this out or not?  If we do, would we want the data to be structured (i.e. a dropdown for copyright type, a text field for supplementary info) or unstructured (i.e. a text field)?  And where would the data come from?

**Comment by seeReadCode** [comment]
Also consider https://commons.wikimedia.org/wiki/Commons:Attribution_Generator

**Comment by seeReadCode** [comment]
If this isn't an active ask, I'm going to close it.

**Comment by seeReadCode** [comment]
K, this one is active. I'll edit more in the main text above to clarify requirements.
