### ISSUE TITLE
Coyote Scavenger Hunt - updating organization name

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#213]
So I realized that because we are MCA Chicago in Coyote our name is not displayed as Museum of Contemporary Art Chicago in the Coyote Scavenger Hunt interface. Can this be updated? I'm ok if solution is a hard code on the scavenger hunt side.

screenshot of organization, and side by side layout of scavenger hunt design:
![screen shot 2018-09-13 at 12 03 51 pm](https://user-images.githubusercontent.com/8040710/45503885-d349e400-b74d-11e8-9e0a-717f4bc25a03.png)
![screen shot 2018-09-13 at 12 01 22 pm](https://user-images.githubusercontent.com/8040710/45503886-d349e400-b74d-11e8-9be7-3763cee944f9.png)

**Comment by sinabahram** [comment]
Let’s please avoid hard coding anything, much less names of entities.

 

I’m not sure I understand the issue. Can you not simply change your name in Coyote?

**Comment by alavatelliMCA** [comment]
There isn't an option for me to edit my organization, I can only add a new one.

**Comment by alavatelliMCA** [comment]
#248
