### ISSUE TITLE
Header styles?

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#224]
Hi since the headers are in all caps I wondered how they were typed in on the backend in case of style change. Are they typed in as Header style, sentence style, or (fingers crossed not) all caps? When I provide content edits I'd like to be consistent with the style already in place.

Ideally we would have sentence style in all places.

e.g.
"Thanks for playing!"

**Comment by sinabahram** [comment]
I also agree with no all-caps. This is an accessibility issue as well.

**Comment by stacietaylorcima** [comment]
All words on the backend are coded "sentence" style and had `text-transform: uppercase` sass applied to it. So, just so that I'm certain of the task at hand: **Nothing should be uppercased anywhere in Scavenger Hunt.** Can you confirm this is the intention here? Thanks! 

@alavatelliMCA @sinabahram

**Comment by sinabahram** [comment]
I don’t wish to speak for Anna, but please assume this is true unless if explicitly not, because that is an accessibility issue and nothing should be all caps.

**Comment by alavatelliMCA** [comment]
Great to hear, all is wonderful. We'll provide edits in sentence style when we do our editorial review. Closing this out.
