### ISSUE TITLE
Thanks for playing page text updates

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#225]
Please update the text on the "Thanks for playing!" page to match text below the username email fields about Coyote in the smaller type size (same as the "Your email is required..." style)
https://live.coyote.pics/scavenger/player 

Thanks for playing!
Enter a username to submit your score
Your email is required for rewards. Only your username is displayed on the leaderboard.
[username and content entry fields here]
Did you know that the Coyote Scavenger Hunt uses descriptions we created to help visitors who are blind or low-vision enjoy artworks and cultural objects? Learn more at [coyote.pics](https://coyote.pics).

**Comment by susanchun** [comment]
Just noticed, can we use "prizes" instead of "rewards" to be consistent with language in signage, etc?

Your email is required for prizes. Only your username is displayed on the leaderboard.
