### ISSUE TITLE
Adjustments to assignments list display

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#235]
https://staging.coyote.pics/organizations/1/memberships/70
Text styling is not showing up, see underlines which should be creating italic text here:`Tamar-kali, _Demonfruit Blues_`

The assignment list should show status of each thing, whether described or not. Clicking on image should jump you two it's resource page, not the assigment page that contains no new information.

**Comment by flipsasser** [comment]
Markdown happens in resource names so this is not an issue - although I'm not a fan of the fact that it _is_
