### ISSUE TITLE
Authors not displayed in description list view

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#237]
https://staging.coyote.pics/organizations/1/representations

Need to open description to see who wrote it. Not the end of the world, but worth fixing.

**Comment by sinabahram** [comment]
Let me know if this is due to me missing it, but it seems like some of these tickets are not getting sorted into our “nice to have”/”must have”/etc. buckets. Anna, may I ask that this happen? if it’s happening, and I’m just missing it, then sorry about that. I see it on some, but not on all.

**Comment by flipsasser** [comment]
This is an incidental fix of my design refactor - I'm closing it here just to cull some tickets. It will ship shortly.
