### ISSUE TITLE
Reject doesn't change description status

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#244]
Reject doesn't change description status.

**Comment by stacietaylorcima** [comment]
Hey @alavatelliMCA! Can you give me more details about where this is happening for you? I'm rejecting from the Ready to Review queue and it seems to be working, so I'm thinking there is another place this is broken for you. Let me know what you're experiencing. Thanks! 

Video of me walking through my experience with the rejection process on staging and successfully rejecting a description: https://drive.google.com/file/d/12q4-bNPAxXrUbrSxRBydfu_rMMP98VMe/view?usp=sharing

**Comment by alavatelliMCA** [comment]
It does seem to be working now! 

However, 
1. we still have the problem that I am sent to the description page instead of remaining on the dashboard to continue approving and rejecting. 
2. Also, when I hit the back button to go back to approving I need to reload the page to make it go away so I can get to the others.
3. The Not Approved tag looks to be the same color as ready to review, I think we had expected this to be red–did we intentionally change it for a reason I can't recall right now?

**Comment by stacietaylorcima** [comment]
Closing this because the initial bug has been solved and the comments provided are included in issue #246.
