### ISSUE TITLE
Sort order: Resources should be reverse chron from creation

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#247]
I can't figure out the display order of resources. On old coyote it is most recently added to the website first to oldest (reverse chron), this works well because we can quickly see if the API loses connection.

Additionally, right now I am trying to check that the data imported properly from the last SQL dump from old coyote and I can't figure out a way to check the records when the lists are in completely different orders.

Additionally once live we will need to be able to check that the resources are properly syncing to the site.

**Comment by alavatelliMCA** [comment]
I can't figure out the sort order of resources, this means I have no way to check the data import for accuracy. 
https://staging.coyote.pics/organizations/1/resources

I expected it would be by creation date, but creation dates from some records are as follows (order appearing in shown after the date and UTC
Creation dates:
2015-06-29 21:04:42 UTC First
2015-06-29 21:05:15 UTC From the fifth page in
2015-06-29 21:04:42 UTC Second to last page before records with clues that are showing up last
2018-06-07 19:35:16 UTC Last

Updated dates for these same objects is as follows:
2018-01-09 21:22:03 UTC First
2018-01-09 21:22:03 UTC From the fifth page in
2018-01-09 21:22:03 UTC From second to the last page
2018-06-07 19:37:22 UTC Last

So I cannot discern a sort order.

Weirder (and scarier) yet I searched on records added on 8/30 (the day we did the dump) because I thought it was weird that last image in the list was in June (I had recalled that being a July image), and I found a major discrepancy:
https://staging.coyote.pics/resources/20051
On new coyote this image shows as being created 2018-04-23 22:42:11 UTC
https://coyote.mcachicago.org/images/21175
On old coyote it shows as being created 2018-08-30 22:01:53 UTC (which is correct)

Should I put the date data problem into a separate issue? Do you think it is a data problem from Onix? Let me know how I can help!

**Comment by sinabahram** [comment]
Yes, please most definitely put the date problem in its own ticket and prioritize the hell out of it too.

 

That, just straight up, should not be happening. Sorry, don’t have more at this time. @FlipSasser will need to examine what’s going on there.

**Comment by flipsasser** [comment]
We've implemented sorting w/the new filtering stuff, so I'm going to close this out as well
