### ISSUE TITLE
only 1 clue showing up

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#251]
I've checked in staging and in incognito mode and suddenly when reviewing the interface only one of the 4 clues are appearing. This will slightly hinder our review process.

Thank you!

**Comment by stacietaylorcima** [comment]
@alavatelliMCA Can you confirm that all the clue/hint/question/answer sets you've created are marked with "approved" status? This may be a side effect of the bulk approval issues were facing.

**Comment by alavatelliMCA** [comment]
A ha! I should have checked that first, thank you. This can be closed.


Anna Chiaretta Lavatelli
Director of Digital Media

Museum of Contemporary Art Chicago
220 E Chicago Ave
Chicago, IL 60611
alavatelli@mcachicago.org<mailto:alavatelli@mcachicago.org>
312-397-4047<tel:312-397-4047>
mcachicago.org<http://www.mcachicago.org>
This message is for the designated recipient only and may contain privileged,
proprietary, or otherwise private information. If you have received it in error,
please notify the sender immediately and delete the original. Any other use of
the email by you is prohibited.

**Comment by alavatelliMCA** [comment]
Of course, I have now approved every single description in the system (again) ;) #155 and #202
