### ISSUE TITLE
Prioritization not displaying in resources list view

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#265]
We are missing the toggle-able label in a column priority that was a part of old coyote. 

old coyote:
<img width="1436" alt="screen shot 2018-09-13 at 9 59 31 am" src="https://user-images.githubusercontent.com/8040710/45506130-fbd4dc80-b753-11e8-89b4-bb2100619d8c.png">

New coyote:
![screen shot 2018-09-13 at 12 46 48 pm](https://user-images.githubusercontent.com/8040710/45506253-52421b00-b754-11e8-875a-72055afa78d0.png)

Details re: implementation: 
- The objects marked high appear above all others
- When visualized I would suggest labels of priority to be:  `urgent` / `not urgent` to match the checkbox language
- Ideally these are toggle-able in the list view

**Comment by sinabahram** [comment]
I think a special priority field was presenting nothing but problems for a concept that could be handled with group membership e.g. a priority group for resources. Since we can now have multi-membership in groups, I am closing this out.
