### ISSUE TITLE
Prioritization culls no search results

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#266]
This may be because prioritization is not importing? But I get no results when checking "urgent" and searching.

![screen shot 2018-09-13 at 12 47 07 pm](https://user-images.githubusercontent.com/8040710/45506260-566e3880-b754-11e8-8de3-a21fcff452ab.png)

Also, this checkbox does not remain checked after clicking search (others do).

**Comment by flipsasser** [comment]
This is working now
