### ISSUE TITLE
No Meta exist when you create a new org

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#269]
I think at the least, alt and long should auto-populate. Though we can build these by hand for each org if need be. However, this does mean that we need to build all the scavenger hunt meta for every new org. Potential for error.

**Comment by sinabahram** [comment]
Yes, alt and long and scavenger hunt meta should populate for every new org. that’s a bug, not intended functionality.

**Comment by alavatelliMCA** [comment]
I think this is resolved and can be closed, is there further work to be done? Leaving open and moving to the done column.

**Comment by sinabahram** [comment]
Yes, in fact, this should have been closed by one of Flip’s commits.

 

Stacie, can you do the honors if you can point it to the right commit?

**Comment by sinabahram** [comment]
My suggestion is to put a “make scavenger hunt meta” on the meta page of organizations. We can control the visibility of this control with a flag which maps to a checkbox at organization creation time. this way, it only shows up for folks we want it to, but it becomes an active step the owners of the org have to take to instantiate all the meta.

 

We therefore make sure the organization stays in control while allowing us manageability.

**Comment by flipsasser** [comment]
This was fixed but not marked as completed here
