### ISSUE TITLE
Resource groups from MCA auto added to new orgs and are required - should not be

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#270]
Orgs may or may not use the resource group feature so it should not be required. Also, the resource groups from MCA should not auto-populate in all organizations since those are specific to the MCA.

(Submitting as a separate ticket–rather than groups, I think the core meta _should_ auto-populate, such as `alt` and `long`#269)

**Comment by sinabahram** [comment]
Anna, is a resource group required in some way now explicitly? I agree that MCA’s defaults should be removed there, but perhaps one default group is actually not a bad idea.

**Comment by alavatelliMCA** [comment]
Yes explicitly required, Bridget couldn't create a new resource without assigning it to a group. I'm fine with a default group, perhaps we take a cue from Wordpress "uncategorized."

**Comment by sinabahram** [comment]
Yeah, that’s exactly what I’m thinking.

**Comment by flipsasser** [comment]
This is implemented - it was blocking the API from working effectively _anyways_ and causing havoc in tests, so it was a triple-whammy to go ahead and make it happen. Now all organizations, when created, receive a default "Uncategorized" resource group. All API requests to add resources assign to this default group, unless overridden.

**Comment by stacietaylorcima** [comment]
Closed by a Flip PR recently. Tested it is working as expected now.
