### ISSUE TITLE
Organizations created all gone

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#276]
Bridget and I created 3 organizations on staging yesterday and they are all gone now. Before I recreate them I want to make sure we are in a stable place for doing this testing.

Screenshot I took after creating one of the first of the three–
![screen shot 2018-09-27 at 1 59 31 pm](https://user-images.githubusercontent.com/8040710/46224192-34131800-c31b-11e8-8941-2ff6fbe65952.png)

Screenshot from just now showing MCA Chicago as the only org–
![screen shot 2018-09-28 at 12 34 51 pm](https://user-images.githubusercontent.com/8040710/46224136-0af28780-c31b-11e8-96c9-f9cb32354e89.png)

**Comment by sinabahram** [comment]
Everytime staging is updated, it copies over from production; therefore destroying staging content.

 

Can you create them in production for testing? That way, they’ll also get copied over to staging in the future.

 

In fact, if you do that now, and then we update staging, it’ll copy them over so we can then have you test latest code on staging.
