### ISSUE TITLE
Identifier slug on new resource doesn't auto-populate

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#284]
Is a required field, doesn't auto-populate based on caption (says it will based on title field, but there isn't a title field) 
![screen shot 2018-09-29 at 4 23 36 pm](https://user-images.githubusercontent.com/8040710/46250629-6ea4af80-c404-11e8-9f01-53e411423431.png)

one I created for Shedd: https://live.coyote.pics/resources/21309

**Comment by stacietaylorcima** [comment]
@sinabahram Jumping in to this one. Should setting this string (if the user does not include one) function in the same way that setting the canonical_id does?

**Comment by flipsasser** [comment]
Sorry, we're using "slug" and "identifier" interchangeably, right?

**Comment by sinabahram** [comment]
My understanding is that they are the same. Can we unify this a bit?

**Comment by flipsasser** [comment]
That has been updated to auto-populate that field if left blank
