### ISSUE TITLE
Allow small mistakes in answers?

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#287]
I think we need to loosen the matching so that if a word is mispelled they still get it right. I feel like you had built that functionality.

E.g. I typed chompers the sark and the answer was rejected despite being 1 letter off.

Thanks!

**Comment by stacietaylorcima** [comment]
@sinabahram Should I implement something along the lines of what I had before?

**Comment by sinabahram** [comment]
I think this is a nice-to-have, so please move it appropriately on the projects board. Far more important things on the list right now, so I vote that we move this down. Answers need to be given correctly independent of case, hyphens, and space, right now. that’s good enough until we can circle back.
