### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#289]
#00aec7 SHEDD
#ee3224 SMART

Cultural center can stay blue until we get notice from them.

**Comment by stacietaylorcima** [comment]
Updated staging database with the requested colors. Production doesn't have eiiher of those locations yet, but ping me as soon as they're created and I'll update there as well! :-) @alavatelliMCA 

staging: 
```
 id | organization_id | position |  tint   
----+-----------------+----------+---------
  1 |               1 |        0 | #ff00ff MCA
  3 |               5 |        2 | #0000ff Chicago Cultural Center
  2 |               4 |        1 | #ee3224 Smart Museum of Art 
  4 |               6 |        3 | #00aec7 Shedd Aquarium 
```

**Comment by stacietaylorcima** [comment]
@alavatelliMCA The organization colors were all defaulted back to pink when the database was wiped out, so I just went in and updated the colors again. Let me know if anything is off! 

 id | organization_id | position |  tint   
----+-----------------+----------+---------
  5 |               6 (Graham Foundation)|        4 | #0000ff
  1 |               3 (Shedd Aquarium)|        0 | #00aec7
  2 |               4 (Smart Museum of Art)|        1 | #ee3224
  4 |               1 (Museum of Contemporary Art Chicago)|        3 | #ff00ff
  3 |               5 (Chicago Cultural Center )|        2 | #0000ff

![location colors](https://user-images.githubusercontent.com/25017973/46501988-dd568400-c7db-11e8-9fd7-3740f6fbef3a.png)

**Comment by alavatelliMCA** [comment]
Graham Foundation: 47297E

**Comment by stacietaylorcima** [comment]
@alavatelliMCA All colors are updated and look beautiful in production, so I'll close this issue. Reopen if anything doesn't look right. :-)
