### ISSUE TITLE
Clues added to MCA Chicago disappeared

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#297]
The MCA clues I added are gone on the MCA Chicago account in the scavenger hunt, but when I check live Coyote account they are still there. https://live.coyote.pics/organizations/1/representations

<img width="710" alt="screen shot 2018-10-01 at 10 05 16 pm" src="https://user-images.githubusercontent.com/8040710/46327265-5b414200-c5c6-11e8-8fe1-58845ac16116.png">

**Comment by sinabahram** [comment]
Sorry, but I need to be pedantic. Do you mean on the MCA Chicago organization? not sure what the MCA Chicago account is.

 

When I go to the scavenger hunt on live, I see two clues for MCA Chicago. Are there supposed to be more?

 

Just trying to figure out if it’s a matter of none showing up, only some not showing up, etc.

**Comment by alavatelliMCA** [comment]
I'm clearly losing my mind. Now I see two. I'll finish parsing this feedback and pick up in the AM.
