### ISSUE TITLE
Adjustments to Survey styling

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#299]
- Fix Submit button to bottom, align left
- Increase spacing between questions and answers
- ~~Underline all answers~~

**Comment by stacietaylorcima** [comment]
Question on "Underline all answers":
* Are you asking for them all to be initially underlined? If we do that, won't there be no way to tell when one has been selected since we're using the underline as the indicator that one has been selected? @alavatelliMCA

**Comment by alavatelliMCA** [comment]
Oversight on my part when posting, underline for selected answer only. Thank you for checking.

**Comment by sinabahram** [comment]
In that case, no change is required since this already happens, correct?

**Comment by alavatelliMCA** [comment]
exactly, so the only thing to change here is fixing submit button and increasing space between questions and answers which will only help clarify the underline as the select mechanism. (low priority)
