### ISSUE TITLE
match footer nav underline styling with the underline on the Survey 'submit' button

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#305]
- Location should always be present on game pages (currently not present on “I found it” page and “See all clues” page)
- Reduce underline for H1 slightly globally
- Match hang height of all first elements to where the location item falls on in-game pages.
- Reduce Tracking
- Leaderboard Submit–See Submit button here for correct size of interface nav (footer elements)

Reference for correct sizing, spacing, and underline weight of interface nav elements:
https://staging.coyote.pics/scavenger/locations/1/survey

**Comment by stacietaylorcima** [comment]
**Question on "Reduce underline for H1 slightly globally":** 
* There doesn't seem to be any default underline on H1's. Can you point to somewhere specific I can see this style so I can track down it's origin? Thanks! @alavatelliMCA

**Comment by stacietaylorcima** [comment]
Question on "Match hang height of all first elements to where the location item falls on in-game pages.": 
* Could I get a screenshot on what this means?

**Comment by stacietaylorcima** [comment]
**Question on "Leaderboard Submit–See Submit button here for correct size of interface nav (footer elements)":** 
* Can I get screenshots for this too?

**Comment by alavatelliMCA** [comment]
Working on this may be best to have a quick call with our Design Director, will send his contact information.

**Comment by alavatelliMCA** [comment]
Disregard:
~~"Match hang height of all first elements to where the location item falls on in-game pages."~~
~~"Reduce underline for H1 slightly globally"~~

Just the third question, as shown in screenshot below, match footer nav underline styling with the underline on the Survey 'submit' button (underline width and spacing from the baseline)–
![screen shot 2018-10-02 at 4 55 55 pm](https://user-images.githubusercontent.com/8040710/46379718-57b0c800-c665-11e8-90b6-ff28c9975256.png)

**Comment by stacietaylorcima** [comment]
@alavatelliMCA I chatted with Sina about this issue a few weeks ago and we've come to conclude we can either have a *text area* with 4 lines of spacing *or* a *text field* that has styling that looks like the design guide. There is not a way for us to move that placeholder down to the bottom. Which would you prefer?
