### ISSUE TITLE
Leaderboard page adjustments

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#307]
If ‘click to expand scores’ is not going to be functional by the launch, let’s loose this line. If it remains, increase spacing between it and leaderboard.

**Comment by stacietaylorcima** [comment]
I'll get rid of it for right now since we are on a time crunch and I'll have you make a separate issue asking for the feature and describing what it should look like and do! That way if I do have time to tackle it, I can. But if not, it's all cleaned up anyway! @alavatelliMCA

**Comment by alavatelliMCA** [comment]
Sounds good.
