### ISSUE TITLE
Leaderboard functionality

### ISSUE THREAD

**Issue by susanchun** [coyote-team/coyote#308]
Sorry if this has been covered. I wanted to try to understand the leaderboard functionality and capability, which at the moment aggregates scores across all locations but doesn't allow for a view of all scores at a particular location, right? Would we, in future, be able to see scores BY location? Would this work with the idea that we envisioned of defining a game with its own scoreboard? For later, of course.

**Comment by sinabahram** [comment]
Including @FlipSasser since scoreboards should be scoped to organization.

**Comment by alavatelliMCA** [comment]
I am closing and pointing to other tickets to answer this question based on our discussion yesterday and Stacie's break out of the tasks.

The Leaderboard was always designed to be global, we adjusted scope by removing the click to expand scores feature #307 and set this functionality to table for later here #223 which apparently created confusion. If click to expand is implemented users could see their score at each location. 

Results of our call is here: #354 and that resulted in these tickets created to adjust that scope:
#359 , #360 , #361
