### ISSUE TITLE
Admin: User creation shouldn't fail with invisible errors

### ISSUE THREAD

**Issue by seeReadCode** [coyote-team/coyote#31]
Reported by sina

**Comment by seeReadCode** [comment]
@sinabahram I couldn't replicate this issue and I don't see any validation errors in the logs which suggests to me that it may have been an HTML5 form error.  

Could you give replication instructions for the bug starting from loading the [form here](http://coyote.mcachicago.org/users/sign_up)?

**Comment by sinabahram** [comment]
That is not the same form I was presented with. That form has the first three same fields e.g. first name, last name, and email, but this form then has password-related fields, which I was definitely not presented with.

 

Good news, that answers the validation error issue, but bad news, why/how did I get served the wrong form across multiple refreshes?

**Comment by seeReadCode** [comment]
There are login, sign up and forgotten password.  I'm not seeing any other form you could have come up against.

**Comment by sinabahram** [comment]
I logged in, and I then went to users, and I went to “new user” and the form I was presented did not ask to assign the user a password, only for the first name, last name, email address, and a checkbox for admin.

**Comment by seeReadCode** [comment]
Ah, so it's not the new user registration but the admin new user form.  I will take a look at that page.
