### ISSUE TITLE
Credits page

### ISSUE THREAD

**Issue by susanchun** [coyote-team/coyote#310]
We have realized that we do not have an ABOUT page on the scavenger hunt, which isn’t absolutely essential except that we need to credit the funders. We remembered that there was a “?” icon in the upper right-hand corner at one point, which would have taken you to an about or FAQ page. I'm attaching a screenshot for this. 
<img width="1137" alt="screen shot 2018-10-02 at 5 12 59 pm" src="https://user-images.githubusercontent.com/639747/46380131-d2c6ae00-c666-11e8-948b-11171ce3b3c1.png">

We don’t want to add extra work to the already full load, though, so we are open to solutions. We can certainly add a credit line to either the main page (“WELCOME TO COYOTE”) or the thanks page or both without adding a whole new page, but we thought we should defer to you about what’s practical. 

--
 
Text options below for short (add to existing main page and thanks page) or long (new credits page)
 
If we are keeping the text minimal and just adding to existing pages, the text would be:
 
Coyote is generously supported by the John S. and James L. Knight Foundation and Lois and Steve Eisen and The Eisen Family Foundation.
 
If we had a whole ABOUT page, it could contain team credits (PAC ones just made up here) and another redirect to coyote.pics:
 
The Coyote project is an initiative of the Museum of Contemporary Art Chicago and Prime Access Consulting. Originally developed to support the authoring, management, and publication of visual descriptions for web visitors who are blind or have low vision, the project team also advocates for the use of description in other areas of practice for museums and cultural organizations. The generous support of the John S. and James L. Knight Foundation and Lois and Steve Eisen and The Eisen Family Foundation has made it possible for us to share the open-source Coyote software with other institutions and to develop the description-based Coyote Scavenger Hunt. Learn more about Coyote at coyote.pics.
 
TEAM COYOTE
 
For the Museum of Contemporary Art Chicago:
Susan Chun, Chief Content Officer
Anna Chiaretta Lavatelli, Director of Digital Media
Gabriel Melcher, Design Director
Sheila Majumdar, Senior Editor
Bridget O’Carroll, Digital Media Associate
Alexander Shoup, Web Developer
Dorothy Lin, Production Designer
Leah Froats, Associate Editor
Lorenzo Conte, Manager of Planning and Production
Christina Stephens, Publishing Administrative Assistant
Tobey Albright, former Senior Interactive Designer
Shauna Skalitzky, former Web Content Manager and Editor
 
For Prime Access Consulting:
Sina Bahram, Principal
Flip Sasser, Software Lead
Stacie Taylor-Cima, Web Developer

**Comment by sinabahram** [comment]
MCA folks, can you please provide us exact guidance on where the ‘?’ link should go?

 

And, exactly what should be on the resulting page?

**Comment by alavatelliMCA** [comment]
The  ‘?’ link is in the upper right of the landing page. I don't know that it needs to be on any page besides the landing if that simplifies the matter at all.

Thank you!

**Comment by susanchun** [comment]
The resulting page would have the header "About" and then the text block(s) below. The text on the "Welcome to the Coyote Scavenger Hunt" page is probably a good model for the size of the type for this text, since there's a fair amount of it. Let's use "Start over" pinned to the bottom at the bottom of the page. The screenshot above shows the positioning of the "?" at the top right.

<copy>
The Coyote project is an initiative of the Museum of Contemporary Art Chicago and Prime Access Consulting. Originally developed to support the authoring, management, and publication of visual descriptions for web visitors who are blind or have low vision, the project team also advocates for the use of description in other areas of practice for museums and cultural organizations. The generous support of the John S. and James L. Knight Foundation and Lois and Steve Eisen and The Eisen Family Foundation has made it possible for us to share the open-source Coyote software with other institutions and to develop the description-based Coyote Scavenger Hunt. Learn more about Coyote at coyote.pics.

TEAM COYOTE

For the Museum of Contemporary Art Chicago:
Susan Chun, Chief Content Officer
Anna Chiaretta Lavatelli, Director of Digital Media
Gabriel Melcher, Design Director
Sheila Majumdar, Senior Editor
Bridget O’Carroll, Digital Media Associate
Alexander Shoup, Web Developer
Dorothy Lin, Production Designer
Leah Froats, Associate Editor
Lorenzo Conte, Manager of Planning and Production
Christina Stephens, Publishing Administrative Assistant
Tobey Albright, former Senior Interactive Designer
Shauna Skalitzky, former Web Content Manager and Editor

For Prime Access Consulting:
Sina Bahram, Principal
Flip Sasser, Software Lead
Stacie Taylor-Cima, Web Developer

**Comment by sinabahram** [comment]
Thinking out loud:

If we can put it on each page, I feel that would be nice, and hopefully easy to just include, but possibly too complicated since we have different styles and content going on, so Stacie, can you simply put on the page Anna has indicated?

**Comment by susanchun** [comment]
Updated text, assuming that we have a whole credits page:

The Coyote project is an initiative of the Museum of Contemporary Art Chicago and Prime Access Consulting. Originally developed to support the authoring, management, and publication of visual descriptions for web visitors who are blind or have low vision, the project team also advocates for the use of description in other areas of practice for museums and cultural organizations. The generous support of the John S. and James L. Knight Foundation and Lois and Steve Eisen and The Eisen Family Foundation has made it possible for us to share the open-source Coyote software with other institutions and to develop the description-based Coyote Scavenger Hunt. Learn more about Coyote at coyote.pics.

TEAM COYOTE

For the Museum of Contemporary Art Chicago:
Susan Chun, Chief Content Officer
Anna Chiaretta Lavatelli, Director of Digital Media
Gabriel Melcher, Design Director
Sheila Majumdar, Senior Editor
Bridget O’Carroll, Associate Video Producer
Alexander Shoup, Web Developer
Dorothy Lin, Production Designer
Leah Froats, Associate Editor
Lorenzo Conte, Manager of Planning and Production
Christina Stephens, Publishing Administrative Assistant
Tobey Albright, former Senior Interactive Designer
Shauna Skalitzky, former Web Content Manager and Editor
Joe Iverson, former Manager of Planning and Production

For Prime Access Consulting:
Sina Bahram, Principal
Mike Subelsky, Software Architect
Flip Sasser, Software Lead
Stacie Taylor-Cima, Web Developer

Thanks to our partner organizations for participating in Coyote Scavenger Hunt:
Chicago Cultural Center
Graham Foundation
Shedd Aquarium
Smart Museum of Art at the University of Chicago

**Comment by alavatelliMCA** [comment]
Latest (from Susan):


The Coyote Scavenger Hunt uses descriptions that were originally created to help visitors who are or blind or have low vision enjoy artworks and cultural objects. Its software was developed by the Museum of Contemporary Art Chicago and Prime Access Consulting to support the authoring, management, and publication of visual descriptions for web visitors. The generous support of the John S. and James L. Knight Foundation and Lois and Steve Eisen and The Eisen Family Foundation has made it possible for us to share the open-source Coyote software with other institutions and to produce the description-based Coyote Scavenger Hunt. Learn more about Coyote at coyote.pics.

TEAM COYOTE

For the Museum of Contemporary Art Chicago:
Susan Chun, Chief Content Officer
Anna Chiaretta Lavatelli, Director of Digital Media
Gabriel Melcher, Design Director
Sheila Majumdar, Senior Editor
Bridget Reilly O’Carroll, Associate Video Producer
Alexander Shoup, Web Developer
Dorothy Lin, Production Designer
Leah Froats, Associate Editor
Lorenzo Conte, Manager of Planning and Production
Christina Stephens, Publishing Administrative Assistant
Tobey Albright, former Senior Interactive Designer
Shauna Skalitzky, former Web Content Manager and Editor
Joe Iverson, former Manager of Planning and Production

For Prime Access Consulting:
Sina Bahram, Principal
Mike Subelsky, Software Architect
Flip Sasser, Software Lead
Stacie Taylor-Cima, Junior Developer

Thanks to our partner organizations for participating in Coyote Scavenger Hunt:
Chicago Cultural Center
Graham Foundation
Shedd Aquarium
Smart Museum of Art at the University of Chicago

**Comment by alavatelliMCA** [comment]
This appears to be implemented so I am closing
