### ISSUE TITLE
Sort order of descriptions inconsistent

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#315]
There is also a ticket about the resources that also have sorting issues here #247 

Not only do I have no idea what the sort logic is, I'm finding that if I do the same sort on both coyotes I get different results as shown in the screenshots below these attempts to share links as well

sorting on metum:
https://coyote.mcachicago.org/descriptions?q%5Bs%5D=metum_id+asc
https://staging.coyote.pics/organizations/1/representations?q%5Bs%5D=metum_id+asc

old coyote:
![screencapture-coyote-mcachicago-org-descriptions-2018-10-03-12_56_37](https://user-images.githubusercontent.com/8040710/46429359-d5c7aa00-c70b-11e8-9ffa-e0431be5b125.png)

staging coyote:
![screencapture-staging-coyote-pics-organizations-1-representations-2018-10-03-12_54_36](https://user-images.githubusercontent.com/8040710/46429267-98fbb300-c70b-11e8-9eaa-67745ccacb4d.png)

sorting on status:
https://coyote.mcachicago.org/descriptions?q%5Bs%5D=status_id+asc
https://staging.coyote.pics/organizations/1/representations?q%5Bs%5D=status+asc

old coyote:
![screencapture-coyote-mcachicago-org-descriptions-2018-10-03-12_49_26](https://user-images.githubusercontent.com/8040710/46429231-897c6a00-c70b-11e8-82a7-55da6b640a10.png)

staging coyote:
![screencapture-staging-coyote-pics-organizations-1-representations-2018-10-03-12_49_07](https://user-images.githubusercontent.com/8040710/46429232-897c6a00-c70b-11e8-8ef9-39fa6bd3557a.png)

**Comment by alavatelliMCA** [comment]
sorry uploaded one screenshot incorrectly! Please view on github for the correct screenshots.

**Comment by sinabahram** [comment]
@FlipSasser this is what’s blocking the data migration from being closed out.

**Comment by flipsasser** [comment]
We now obey ordinality and enforce it across the board, so we can safely close this out
