### ISSUE TITLE
Investigate (and possibly remove) `identifier`

### ISSUE THREAD

**Issue by flipsasser** [coyote-team/coyote#319]
It looks an awful lot like we don't need or use the `identifier` column in any relevant way. Investigate whether or not we can remove it, and if we can, please remove it!

**Comment by sinabahram** [comment]
I think this has been done with data model work and is related to the issue I closed around slug. @flipsasser  can you close if you agree?

**Comment by flipsasser** [comment]
This was in fact wrapped up in the data model review
