### ISSUE TITLE
Design updates from Tobey

### ISSUE THREAD

**Issue by seeReadCode** [coyote-team/coyote#32]
Short term
- [x] 3x grid for home view
- [x] leaderboard 

Accomplished
- [x] new fonts
- [x] user dropdown
- [x] fixed header
- [x] better announcement treatment
- [x] blue for input fields
- [x] label treatments
- [x] tabbed login/signup
- [x] oo to word mark and back during page transition
- [x] focus state for non-input keyboard v. mouse (ask sina for code)

**Comment by seeReadCode** [comment]
Relates to #5 #16 #29 #26 #25

**Comment by seeReadCode** [comment]
this commit was  related as well https://github.com/coyote-team/coyote/commit/9e1eccba876e8da57679f70caadbde28f977cbe5

**Comment by seeReadCode** [comment]
Other leaderboard component ideas:
- graphic treatment for key numbers (important totals, numbers that count to 0 and have no reasonable progress indicator such as ready to review count)
- counts for top 5 describers
- show best approval record

Other design ideas:
- more intense visual call to action for priority items
- priority counts in queues
- do we want to show counts across image groups?

**Comment by alavatelliMCA** [comment]
I like the leaderboard component ideas. Do you need a design for graphic treatment?

- Will the priority items be the first to appear in the Queue? They should be pushed ahead of everything. If so I don't know that it needs to be called out more, but will look with Tobey.
- Can you explain what you mean by priority counts in queues? Not following
- I don't think we need counts across groups as the groups are somewhat blurred, but if simple to implement it can't hurt to have.

**Comment by seeReadCode** [comment]
@alavatelliMCA I clarified my text a bit to help answer your questions (and to clarify some of your responses for anyone else following along).

**Comment by seeReadCode** [comment]
@alavatelliMCA please let me know what you are thinking about the leaderboard and what questions you have now re: priority counts etc
