### ISSUE TITLE
Enhancement: Markdown in description text field

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#326]
In some of our hints and clues, titles of exhibitions are referred to so we would want to create italic text in the description text field.

EG Hint 1 from Calder clue
It's in _Heaven and Earth_ 

This was discussed on a call, but unfortunately, no ticket was made. Making this one now, I completely understand if this is a post-launch feature.

**Comment by sinabahram** [comment]
I’m including @FlipSasser because he “thinks” this “may” be easy.
