### ISSUE TITLE
slug / identifier doesn't characater limit to slug friendly characters

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#330]
I just realized that identifier is supposed to be slug.

This ideally should be auto-populated based on the title (as help text states) however it does not and is a required field. In my rush, before realizing this I was duplicating the title to the field assuming it would correct to slug style, but now see that it doesn't.

Will triage later.

https://live.coyote.pics/resources/21331

**Comment by sinabahram** [comment]
Anna, this does autopopulate to title. Please don’t copy/paste them in, as then you’re overriding the auto-population.

 

I don’t’ know what happens if you empty that field after having it in there. @FlipSasser, does it then autopopulate if that’s the case?

**Comment by flipsasser** [comment]
Yes, if it's ever blank it will auto-populate

**Comment by sinabahram** [comment]
Awesome. In that case, @ALavatelliMCA, please delete any slugs and they’ll autopopulate from title.

**Comment by alavatelliMCA** [comment]
Sounds like this has no purpose, if so can we just lose it?

**Comment by sinabahram** [comment]
We will revisit if this is still a concern.
