### ISSUE TITLE
Markup changes to games finish

### ISSUE THREAD

**Issue by stacietaylorcima** [coyote-team/coyote#340]
Put the yes and no options in a ul as li's.

**Comment by stacietaylorcima** [comment]
"confirmation" id on "Are you sure you want to end the game?"

ul add aria-labelledby="confirmation"

**Comment by stacietaylorcima** [comment]
@sinabahram Sorry to pester you, but in the source code below is there somewhere else I needed to add the confirmation id here? I feel like we talked about adding it to the "Are you sure..." text too? 
```
<h1>Are you sure you want to end the game?</h1><ul aria-labelledby="confirmation"><li><div class="title"><a href="/scavenger/games/26/finish?confirm=true">Yes!</a></div></li><li><div class="title"><a href="/scavenger/games/26/clues">No! I want to keep playing!</a></div></li><li><div class="title"><a href="/scavenger/locations">No! I want to keep playing at a new site!</a></div></li></ul>
```

**Comment by stacietaylorcima** [comment]
I pushed these commits up so that I'd have them in, but I have a suspicion that I didn't do this quite right because I feel like we talked about the phrase "Are you sure you want to end the game?" should be wrapped in the confirmation label? @sinabahram

**Comment by sinabahram** [comment]
I thought we had established good notes on this and the other markup issue, so I’m confused why this markup is incorrect?

 

you don’t have an ID on the heading. You point to “confirmation” with aria-labelledby, but where is “confirmation”? you must point to something that exists, and so you need an ID on the heading whose value is confirmation  … which you can achieve with id=”confirmation” on the heading tag.
