### ISSUE TITLE
Add title and longdesc to all image placements if available

### ISSUE THREAD

**Issue by seeReadCode** [coyote-team/coyote#35]
How should we render longdesc?

**Comment by sinabahram** [comment]
This is a longer conversation that needs to occur. We need to have a widget that displays both alt and longdesc, possibly with a picker or some other kind of selector control that can be mostly minimized/collapsed. One could imagine a box to the right of an image or other forms of widget e.g. one that replaces widgets with descriptions (purely as an example, not as a production version).

 

We should also not use longdesc per say, but this widget to be implemented will guide/dictate how this description should be stored.

**Comment by seeReadCode** [comment]
We are looking `aria-details`, pending decision.
