### ISSUE TITLE
Unable to upload image on new resource

### ISSUE THREAD

**Issue by bridgetocarroll** [coyote-team/coyote#352]
Hi y'all,

Wanted to note that as I've been adding new resources for the scavenger hunt I'm unable to upload images for them.

Tried to put images in for the new resources via the uploader. Did the Graham Foundation organization ones and not seeing any:
https://live.coyote.pics/resources/21339

whatsmybrowser.org/b/X7Q676M

Thanks,

Bridget

**Comment by flipsasser** [comment]
Yup, I updated mine to "Physical Object" and it no longer renders the image. I'll fix.

**Comment by alavatelliMCA** [comment]
Ah technically according to the data structure, we should actually be uploading as images not physical objects and then making the image a part of the physical object... that's a problem for another day. 

If easier we can change from physical objects to images!

Thank you!!!

**Comment by bridgetocarroll** [comment]
Ah, makes sense, my bad!

**Comment by flipsasser** [comment]
Well I can still detect if the attached file is renderable as an image, so I'll do that regardless!

**Comment by sinabahram** [comment]
Exactly correct. there should be a link to the physical object. A physical object’s render is meaningless, unless we hook Coyote up to Star Trek replicators or something. An image’s render is of course meaningful as is audio, video, etc.

 

I don’t think any change is required here, right? There’s just some data entry that has to happen to respect the datamodel.

 

@FlipSasser, I hesitate to make changes on this as it’s not actually a bug what-so-ever and would involve undoing some assumptions and features basic to new Coyote.

**Comment by sinabahram** [comment]
I think we should stick to the years-old data plan here … resources can be made, and if a representation depicts a physical resource, then we use the appropriate fields to indicate this per our data model. Things that are of type image, do in fact render correctly.

**Comment by flipsasser** [comment]
I'm going to close this out pending a longer discussion
