### ISSUE TITLE
License? Support links?

### ISSUE THREAD

**Issue by seeReadCode** [coyote-team/coyote#36]

**Comment by sinabahram** [comment]
Any objections to mpl v2?

**Comment by alavatelliMCA** [comment]
mpl?

**Comment by seeReadCode** [comment]
http://choosealicense.com/licenses/mpl-2.0/

**Comment by susanchun** [comment]
I have only ever used the LGPL and GPL. Can someone provide the diffs with MPL?

**Comment by sinabahram** [comment]
https://www.mozilla.org/en-US/MPL/2.0/

**Comment by seeReadCode** [comment]
@susanchun this site gives very concise explanations and comparisons: <http://choosealicense.com/licenses>

Compared to the LGPLv3, MPL limits trademark use but doesn't require changes to the code to be noted.  It's effectively a slightly weaker LGPL.  Would you agree @sinabahram?

**Comment by sinabahram** [comment]
I would agree, but it makes me think that lgpl is possibly the way to go. I have to get into the right mindset for sitting down and slogging through licenses (oh joy…). More from me on this in a bit.

**Comment by seeReadCode** [comment]
I set MPLv2 in a commit a while ago.  I'll leave the issue you open until you make up your mind.

**Comment by seeReadCode** [comment]
@susanchun I'm closing this for now
