### ISSUE TITLE
Leaderboard: Make global

### ISSUE THREAD

**Issue by stacietaylorcima** [coyote-team/coyote#360]
Leaderboards must be global and not scoped to an individual location. This very well may already be the case, but we need this confirmed. Clues must be the total of all organization's clues. Time must be total of all time a user spent at all locations.

**Comment by flipsasser** [comment]
Per the comment from @sinabahram on https://github.com/coyote-team/coyote/issues/308, I put together this PR https://github.com/coyote-team/coyote/pull/278. I'm confused as to what we actually want - can someone please clarify for me what I'm missing?

**Comment by sinabahram** [comment]
Let’s discuss via voice. This is actually clear, but I think it has gone through multiple revisions, and super complicated by the insistence of location scoping from MCA late in the process.

 

The good news is that I believe 90% of this is already implemented.

**Comment by flipsasser** [comment]
I restored the old behavior here.
