### ISSUE TITLE
Leaderboard: Sorting

### ISSUE THREAD

**Issue by stacietaylorcima** [coyote-team/coyote#361]
Entries on the leaderboard should be sorted in the following way: 

- Number of clues completed - descending
- Then by time - ascending
- Then by locations count descending
  - Note: where locations count is the number of locations with at least 1 correct answer.

**Comment by flipsasser** [comment]
What do we define as "time" here? Game ended_at - game started_at?

**Comment by flipsasser** [comment]
Barring feedback on time - and considering the non-trivial nature of this problem - I've shipped a solution sorting by clues and locations completed. We can pursue time once the interstitial stuff is finished.

**Comment by alavatelliMCA** [comment]
yes, total game time from start to end.

**Comment by alavatelliMCA** [comment]
Sorry that is adding up time at all locations, does that make sense? I am on slack and can chat if useful.
