### ISSUE TITLE
Remove "change locations" next to COYOTE header

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#365]
It seems that we can remove padding on the COYOTE header to accommodate the addition of "change locations" reviewing the layout against the designs this seemed like an ideal solution. 

reducing this gap should resolve the layout issues caused by the addition.

![screen shot 2018-10-05 at 12 44 40 pm](https://user-images.githubusercontent.com/8040710/46553631-9af87a00-c8a3-11e8-9200-323c2fdf8cfd.png)

**Comment by alavatelliMCA** [comment]
There was a total misunderstanding, we are going to remove change location
this solves the spacing issue and several other issues that I didn't understand until now.

updating ticket to remove "change location"

and SORRY.

**Comment by stacietaylorcima** [comment]
@alavatelliMCA Lol! No problem. So, remove change location from all headers?

**Comment by sinabahram** [comment]
Yes, essentially completely back out that commit. Hopefully if this was phrased as a single commit, which I think it was, it should be a quick undo of that commit. Work with @FlipSasser if you have any issues with git on this.

 

 

President, Prime Access Consulting, Inc.

Twitter: @SinaBahram

Company Website:  <https://www.pac.bz> https://www.pac.bz

Personal Website:  <https://www.sinabahram.com> https://www.sinabahram.com

Blog:  <https://blog.SinaBahram.com> https://blog.SinaBahram.com
