### ISSUE TITLE
Addition of interstitial page and adjustments to make the score per location game logic work

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#369]
1. delete the "Change Location" link that was recently added.

2. Change the "End Game" link to say, "I'm Done". This link points to the
interstitial page in #3

3. Add an inerstitial page that has three links on it with some explanatory
text:
**When you switch to a new site you cannot go back. Are you sure you’re done?
No! I want to keep playing where I am.
Yes! I want to start at a new site.**

Locked to bottom of the screen we include the end game link that takes you on the end game path already created–
**End game**

	3.A: If the agree and change location link is selected, then the
player is taken to the original "Where are you" screen. it is important to
make sure that any previously played locations are no longer links since we
already told them they can't play those more than once. Just remove the link
tag, and this will remove the underline, and we're fine. Note, include an "End Game" link on the locations page, **after** at least one location has been played, to make sure that users who get to that screen can still have the option of ending the game easily. 

	3.B: If any "end game" link is pressed, then we follow our standard
flow e.g. ask for player name and email and take them to the leaderboard,
etc. (no changes here).

	3.C: If the "go back to [location name]" links is pressed, then we
simply return the user to that context where they were so they can continue
that location's hunt.

4. Timing is now deterministic and reasonable again because times are the
sum of any times spent in each location. How do we know the times spent on a
location? It's the time of the first clue until the time they press either
the "change location" or "end game" links on the interstitial page.

5. the leaderboard is global as coded now (I believe no changes required
here either).

**Comment by stacietaylorcima** [comment]
@flipsasser 

Step 1: delete the "Change Location" link that was recently added. has been COMPLETED with PR #372 as related to issue #370

**Comment by flipsasser** [comment]
A clarification on Sina's specs:

- When players select "I'm done," they can either
  1. Return to the location and continue playing
  2. End that location and select a new one or
  3. End all locations and register their name / email

**Comment by alavatelliMCA** [comment]
Yes, but we should actually still send them to the are you sure you want to stop playing and submit your score screen.

**Comment by sinabahram** [comment]
Glad you said that. Flip and I arrived at the exact same conclusion on our call.

**Comment by alavatelliMCA** [comment]
I believe End game should update to "I'm done" globally. Except for the two actual instances of end game we have created, which now means end scavenger hunt session for all locations.

**Comment by sinabahram** [comment]
Same for me. that sounds exactly correct.

**Comment by flipsasser** [comment]
@sinabahram @alavatelliMCA this is up on staging and production. Please test thoroughly!

**Comment by alavatelliMCA** [comment]
It is AWESOME. Thank you, going to do another round of testing.
