### ISSUE TITLE
Coyote Bookmarklet

### ISSUE THREAD

**Issue by seeReadCode** [coyote-team/coyote#37]
We are using https://github.com/seeread/easymarklet to simplify the iframe injection etc.

How are we injecting descriptions:
- override `alt` 
- sighted widget (consider MCA)
- Eventually we may want to accept any objects with background images.

Clicking the bookmarklet
- [x] with auth token available for ajax request
- [x] displays images in a grid with describe overlays
- [x] displays current version
- [x] parses the website host 
- [x] and then gets website id (via get websites, then post if necessary)
- [x] on describe click, gets image id (via get images with website id filter, then post if necessary), then opens describe window 
- [x] consider http://ignitersworld.com/lab/jsonQ.html
- [x] allows user to dismiss overlay
- [x] injects iframe with src of current bookmarklet
- [x] change url method on image model to allow for absolute path without website, absolute starts with `//`, relative with `/`
- [x] a bookmarklet generator for the home page that allows people to generate the bookmarklet code with their token in it'
- [x] pre-populate description with alt 
- [x] add available image annotations to original page
- [x] sighted description widget
- [x] better error display
- [ ] message/redirect for if session not open 
- [ ] design tweaks
- [ ] test across sites listed below
- [ ] check if iframe is there

Later
- [ ] add page url on follow up describes
- [ ] make overlay accessible (keyboardable, focus lock)
- [ ] move iframe focus
- [ ] accessible iframe dismissal
- [ ] how should we use group id?
- [ ] fuzzy matching for http/s?
- [ ] will need HTTPS on server, see #20 
- [ ] can we remove user email/token from the bookmarklet and replace with a session check?

**Comment by seeReadCode** [comment]
@sinabahram I'll be starting on this in earnest tomorrow.

**Comment by sinabahram** [comment]
If we can, let’s synch up before you do?

**Comment by seeReadCode** [comment]
@sinabahram will do

**Comment by seeReadCode** [comment]
Sites to consider:
- http://mcn.edu/
- https://noma.org/
- The Menil Collection
- The Historic New Orleans Collection
- Museum of Applied Arts and Sciences
- Art Gallery of New South Wales
- Yale Center for British Art
- Nasher Sculpture Center
- Corning Museum of Glass
- Minneapolis Institute of Art
- National Museum of the American Indian
- Emory University Libraries
- Amon Carter Museum of American Art
- The Museum of Fine Arts Houston
- M+
- The Field Museum

**Comment by seeReadCode** [comment]
Injection descriptions:
- sightless 
- sighted widget

**Comment by seeReadCode** [comment]
@sinabahram please send or add description/mockup for sighted widget with annotations

**Comment by sinabahram** [comment]
This has been done but off of git for now since designs/thinking is not finalized for public consumption.

**Comment by sinabahram** [comment]
closing this out as too many things have changed since then.
