### ISSUE TITLE
Order of Queue

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#39]
Hi, what order does the queue presented to admin represent?

Thank you!

**Comment by seeReadCode** [comment]
@alavatelliMCA could you screenshot and describe which queue you are asking about?

**Comment by seeReadCode** [comment]
@alavatelliMCA please see my question

**Comment by alavatelliMCA** [comment]
I have no idea what order this is, seems kind of random.

![screen shot 2016-09-20 at 5 01 10 pm](https://cloud.githubusercontent.com/assets/8040710/18690472/e074bfee-7f53-11e6-9ac7-ecadf6219927.png)

**Comment by seeReadCode** [comment]
They are sorted to show, in order of precedence, first the priority items and then reverse chronological order (according to the created timestamp from MCA).  I've added a border around priority items to make this a bit clearer.  I also added the updated and created timestamps to the image and description detail pages for reference.

**Comment by alavatelliMCA** [comment]
I see the source of my confusion, I thought the sort was wrong because the images at the top aren't the most recent. It looks like Coyote stopped pulling images from the website around August 12. I'll make a new issue for this to track, will check in with Tomas if anything changed around then.

**Comment by seeReadCode** [comment]
I bet it's related to this deploy on my side.  https://github.com/coyote-team/coyote/issues/34  I'll look at it today.  Don't bother Tomas yet please.

**Comment by seeReadCode** [comment]
That new issue is #44 .  I'm closing this one for now.
