### ISSUE TITLE
Users not finishing

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#407]
Low priority, but logging the first learning of the day. Users don't "end game" and submit their score even when there are good prizes. 
This is technically ok, as we explicitly state that you need to submit your email to win prizes/finish the game.

One user had an issue on our wifi and couldn't get his phone to reconnect, so we took down his name and email. He finished MCA clues around 1:20, but of course, never ended the game.

**Comment by sinabahram** [comment]
closing this, but it'll be around if we reuse this module in the future.
