### ISSUE TITLE
updating representation breaks layout

### ISSUE THREAD

**Issue by tomasc** [coyote-team/coyote#409]
updated representation of https://staging.coyote.pics/representations/3175, layout broke, see screenshot:

<img width="1525" alt="46743625-c3201880-cca9-11e8-9cc9-8cf9f184ee36" src="https://user-images.githubusercontent.com/3788/46748208-5f025200-ccb3-11e8-8990-4a4438c647eb.png">

**Comment by tomasc** [comment]
Dear @stacietaylorcima unfortunately I don't know how should this look like. One thing I noticed are Ruby Arrays outputed as Strings – ie `[nil, ""]` or `["Banguqet …"]`. It is not pretty nor readable.

**Comment by sinabahram** [comment]
Closing this for now until some updated usecases point out an issue, especially given that the underlying screen may be touched up soon.
