### ISSUE TITLE
resources API endpoint with updated_at_gt does not return freshly updated representations

### ISSUE THREAD

**Issue by tomasc** [coyote-team/coyote#410]
I have updated this records' representation https://staging.coyote.pics/representations/3175, however when trying to query for representations updated since last 30 minutes I am getting back empty Array.

Without this working properly we are unable to keep the MCA website in sync with Coyote.

See response here:

```ruby
{"data":[],"links":{"self":"https://staging.coyote.pics/api/v1/organizations/1/resources?filter%5Bupdated_at_gt%5D=2018-10-10T08%3A36%3A05-05%3A00\\u0026filter%5Bwith_approved_representations%5D=true\\u0026page%5Bnumber%5D=1\\u0026page%5Bsize%5D=100","first":"https://staging.coyote.pics/api/v1/organizations/1/resources?page%5Bnumber%5D=1\\u0026page%5Bsize%5D=100\\u0026q%5Bupdated_at_gt%5D=2018-10-10T08%3A36%3A05-05%3A00"},"jsonapi":{"version":"1.0"}}
```

When I query for a longer time period (let's say 10 days) I get data back. Perhaps a caching issue on your side?

**Comment by flipsasser** [comment]
@tomasc ah I see, this query is filtering against resources', not their representations', `updated_at` column.

I added an additional filter option named `resources_updated_at_gt` which will do what you'd like it to do. The PR is going through the test cycle now, and when it wraps up I'll merge it!

**Comment by tomasc** [comment]
@flipsasser I think you meant `representations_updated_at_gt`, correct?
If so, then this seems to work.

**Comment by flipsasser** [comment]
Roger dodger, closing this two years later then
