### ISSUE TITLE
the POST API endpoint should also accept updates

### ISSUE THREAD

**Issue by tomasc** [coyote-team/coyote#411]
Would it be possible for `POST /organizations/:organization_id/resources` to also accept existing resources, and in that case simply update them with new values? This would simplify things dramatically (otherwise a site would have to store Coyote internal id, compare timestamps or make multiple requests etc. etc.).

Currently the response is:
```ruby
{"errors"=>[{"title"=>"Invalid canonical_id", "detail"=>"Canonical has already been taken", "source"=>{}}], "jsonapi"=>{"version"=>"1.0"}}
```

**Comment by flipsasser** [comment]
Would you like this to match against canonical ID?

**Comment by tomasc** [comment]
@flipsasser yes please

**Comment by flipsasser** [comment]
Okay, the PR is up. Give the tests a few minutes to run and I'll let you know when it's merged and deployed.

**Comment by flipsasser** [comment]
@tomasc the fix is on staging

**Comment by tomasc** [comment]
@flipsasser this works, thanks

**Comment by jscholes** [comment]
Closed as this seems to have been resolved in https://github.com/coyote-team/coyote/pull/414.  @flipsasser, @tomasc - please reopen if this is incorrect.
