### ISSUE TITLE
API resources JSON missing link back to Coyote

### ISSUE THREAD

**Issue by tomasc** [coyote-team/coyote#412]
This would be helpful so that we could provide a link back to Coyote in the MCA website CMS

**Comment by sinabahram** [comment]
I think @FlipSasser already had this on his radar or already pushed a fix for this. Flip, can you clarify, please?

**Comment by flipsasser** [comment]
@tomasc my bad, in my mad rush a few weeks back I added this to just the `resources/:id` endpoint. I've updated it so all resources come back with a `coyote` key in their `links` dictionary.

**Comment by tomasc** [comment]
@flipsasser great, this works, thank you

**Comment by jscholes** [comment]
Closed as this seems to have been resolved in https://github.com/coyote-team/coyote/pull/414 via https://github.com/coyote-team/coyote/commit/7b0e3bc1e9c4b2815a0875f4e15ffc550ca2d6a6.  @flipsasser, @tomasc - please reopen if this is incorrect.
