### ISSUE TITLE
Image not showing up in Coyote

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#429]
I can't find the hero image on this page, https://mcachicago.org/Exhibitions/2019/Emerge-2019 , in Coyote.

@sinabahram do you think this is something on Tomas' side? I have some old screenshots I can use in the meanwhile for your site.

**Comment by sinabahram** [comment]
Is there a synch that needs to happen? Is the data also missing from staging? Was it there before or never added in the first place?

**Comment by alavatelliMCA** [comment]
New image, if there is a way to see the most recently added images we could probably pinpoint the issue
