### ISSUE TITLE
Artwork caption disappeared

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#430]
Looking at this resource page https://live.coyote.pics/resources/4138
After updating a description on this resource renamed itself to **201143v10.jpg** from the caption name:
**Kris Martin, Belgian, b. 1972. T.Y.F.F.S.H., 2011. Hot air balloon, basket, metal ring, and fans. Dimensions variable. Collection Museum of Contemporary Art Chicago, Gift of Mary and Earle Ludgin by exchange, 2011.43. Photo: Nathan Keay, © MCA Chicago**

Maybe it could be related to the missing image issue if it is sync problem with MCA website? #429

**Comment by sinabahram** [comment]
Closing this as it's super-old.
