### ISSUE TITLE
Data Model?

### ISSUE THREAD

**Issue by musebrarian** [coyote-team/coyote#433]
Is there a published data model for Coyote? The following anchor doesn't seem to go anywhere.

https://github.com/coyote-team/coyote#data-model

We are starting some initial work here and I want to be sure what we are doing is minimally compatible if/when we implement Coyote.

**Comment by sinabahram** [comment]
@flipsasser  can you update the readme with the data model notes we put together and then close this out?

**Comment by flipsasser** [comment]
Donezo, check out https://github.com/coyote-team/coyote#data-model
