### ISSUE TITLE
source file lib/coyote/strategies/mca.rb is not found, 404s from documentation

### ISSUE THREAD

**Issue by visualist** [coyote-team/coyote#435]
From this documentation page:
- https://coyote-team.github.io/coyote/#_Strategies

The following link does not exist:
- https://github.com/coyote-team/coyote/blob/master/lib/coyote/strategies/mca.rb
- in fact there is entirely no folder there

Nor can I find any other example strategy files on any of the branches. I think I've looked at all branches that exist publicly.

Bottom line: it would be wonderful to see an example strategy file, so if mca.rb specifically is not available, maybe some other example could be constructed.

**Comment by flipsasser** [comment]
@visualist we were unable to track down whatever this was referring to. If you'd like some assistance importing resources, let me know and I can work with you directly!
