### ISSUE TITLE
Unmet Dependencies

### ISSUE THREAD

**Issue by musebrarian** [coyote-team/coyote#437]
I've tried to install this on OSX and in a AWS Linux 2 instance, but keep running into the following error. 

The following packages have unmet dependencies:
 postgresql-client-9.6 : Depends: libpq5 (>= 9.6.17) but 9.4.26-0+deb8u1 is to be installed: Unable to correct problems, you have held broken packages.
ERROR: Service 'test' failed to build: The command '/bin/sh -c apt-get install -y postgresql-client-9.6' returned a non-zero code: 100

**Comment by flipsasser** [comment]
@musebrarian apologies for the delay in getting to this - we have a Docker configuration and setup instructions that should make it simple to get up and running.

Debugging Ubuntu may be a little bit outside my comfort zone but I'm happy to try. First thing of note is that we run PostgreSQL 11 - so an `apt-get update` and `apt-get dist-upgrade` may be in order before you continue down this road.

Let me know if the Docker stuff helps or if you need additional assistance.

**Comment by sinabahram** [comment]
Closing this as the underlying issue has been fixed.
