### ISSUE TITLE
Feature request: Batch resource retrieval by source_uri

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#439]
As an API user I would like to query a set of `source_uri` to an API endpoint, to verify whether these already have corresponding resource records for a given organization on coyote's side.

While I could theoretically query _all_ resources and filter, this is algorithmically inefficient and would better be served by a custom database query on coyote's server side.

Potential issues I can think of would be that this is technically a GET request, but could potentially become very large (say, querying 10 or more `source_uri`s at a given time).

Alternatively, an endpoint providing single-record lookup by combination of `organization_id` and `source_uri` would also work in an iterative fashion.

**Comment by zersiax** [comment]
Can you give me an example of what kind of URL you would like to see work?
I think the second option, creating an endpoint to return multiple resources, is simple enough to implement. The gathering of those resources is done serverside and can just be rendered afterwards I would think?

**Comment by jkva** [comment]
@zersiax probably something like

`GET https://staging.coyote.pics/api/v1/resources/[encoded_url1]&[encoded_url2]&[encoded_url3]&...`

This still potentially causes (data) url length issues (413 entity too large), but if we want to maintain a proper REST schema, that's the way to go. Any HTTP error handling is client responsibility.

As a response I'd expect to get a JSON structure with either a `source_uri` to `coyote resource id` mapping, or a `source_uri` to `entire coyote resource` mapping.

**Comment by sinabahram** [comment]
Question: is there a reason why these can’t or shouldn’t be provided as a JSON payload instead of URL parameters given we’re following a JSON API approach?

**Comment by jkva** [comment]
No reason it can't be a JSON payload as the `GET` parameter as well, say `GET /resources?uris=[ ..., ... ]`. Although no other GET requests do so on this API as far as I can tell. It's otherwise consistent in providing JSON responses.

**Comment by zersiax** [comment]
@flipsasser I looked into this today but honestly feel a little lost, we have a sourceURI as well as an identifier field on the Resource model, but neither seem to really be used in the resourceController?
I do see in the routes file that we use the identifier somewhere, but I don't really see what code would handle a query by sourceURI to either extend or replicate for this issue, do you have a code pointer for me?

**Comment by jkva** [comment]
@flipsasser as per the current REST schema and documentation I propose the route

`GET /resources?uris=...`

where `uris` is a JSON-encoded array of `source_uri` fields.

As a return value I expect a JSON object where the keys are the requested source_uris with the associated resource, if any exists.

```
{
  "https://www.example.org/image.png": { ... },
}
```

does that work for you?

**Comment by flipsasser** [comment]
@jkva we follow [JSON:API](https://jsonapi.org/) strictly - can you clarify how the structure you referenced would look in a JSON:API format?

**Comment by flipsasser** [comment]
@jkva belay that - I've added the ability to filter by `source_uri` when requesting resources. You can cram as many in there as the URL will allow. To do so, provide the following query parameter:

`GET /resources?filter[source_uri_eq_any]=url1+url2+url3`

You can separate source URIs with whitespace or commas. This will go live on staging shortly.

**Comment by flipsasser** [comment]
@jkva per the discussion in Slack, I've added an endpoint `POST /api/v1/organizations/{id}/resources/get` which will accept a JSON request body, e.g.

```json
{
  "filter": {
    "source_uri_eq_any": "https://www.google.com/ https://www.yahoo.com/ https://www.altavista.com/"
  }
}
```

This will head to staging soon.

**Comment by flipsasser** [comment]
This is fixed per @jkva
