### ISSUE TITLE
Sync with Website

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#44]
It appears that Images have not been pulled since August 12, I am checking on our end to find out what changes could have caused this.

**Comment by seeReadCode** [comment]
Likely related to #34

**Comment by alavatelliMCA** [comment]
Confirmed, I will wait until further notice before looping in Tomas.

**Comment by seeReadCode** [comment]
Another synchronization bug was addressed here but descriptions that were updated since 2016/08/12 might need to be patched to MCA as well.
 https://github.com/coyote-team/coyote/commit/4061a0e9ba293c240a01495ca43d5e726f3b1624

**Comment by seeReadCode** [comment]
I ran

```bash
TASK="websites:update[64800]" bundle exec cap production rake
```
and that got us updated on our side.

I'm trying to fix this bulk command for patching
```
TASK="websites:patch_bulk[64800]" bundle exec cap production rake
```
and that should get us updated on the MCA side.
