### ISSUE TITLE
Is there a uniqueness constraint on resources?

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#441]
When I create a new resource via the API by posting

```json
{
	"title": "Test",
	"source_uri": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fnl.wikipedia.org%2Fwiki%2FGroucho_Marx&psig=AOvVaw135tY2d7dCS849pHSWUHLJ&ust=1586606863025000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLDx5qbp3egCFQAAAAAdAAAAABAD",
	"resource_type": "still_image"
}
```

to

`https://staging.coyote.pics/api/v1/organizations/1/resources`

I can do this multiple times, each time receiving a `201 CREATED` with resource JSON response body. Even though the `source_uri` is each time the same. Is this by design?

**Comment by flipsasser** [comment]
There is not a uniqueness constraint, but I think there _can_ be one.

```SQL
SELECT
  resources.id,
  other.id AS duplicate_id,
  resources.source_uri,
  other.source_uri AS other_uri,
  organizations.title
FROM
  resources
  JOIN organizations ON resources.organization_id = organizations.id
  JOIN resources other ON other.id != resources.id
    AND lower(other.source_uri) = lower(resources.source_uri)
WHERE
  resources.source_uri IS NOT NULL
  AND resources.source_uri != '';
```

returns 0 results on production. I _will_ have to clear out, like, everything @jkva has done on staging - but hopefully that's okay.

**Comment by sinabahram** [comment]
Just a note that the constraint should be scoped to an org e.g. an org should only ever have 1 resource with a single URI, even if there are dozens of representations describing that resource, or so I feel.

**Comment by flipsasser** [comment]
Ah thanks for that @sinabahram - I'll ensure the uniqueness is scoped

**Comment by flipsasser** [comment]
This is finished and live
