### ISSUE TITLE
What to provide for resource title when none is known?

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#444]
Use-case: creating many resources in iterative fashion.
Problem: the API requires a non-empty `title` field to be provided.

Currently I provide the useless "Image Title" string, but I'd rather provide nothing at all. Is this an option?

**Comment by flipsasser** [comment]
You can now omit the title on staging - it will default to "(no title provided)" in the web interface

**Comment by flipsasser** [comment]
@jkva we have switched to thinking some flavor of a name should be required - are you able to provide the filename in lieu of a proper title?

**Comment by sinabahram** [comment]
And note, if you have the caption from WP, this is where that would go.
