### ISSUE TITLE
Coyote should recognize logged-in users

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#452]
If you go to Coyote 'just the /index route' and are logged in, you get the intro page, but that's not appropriate. If you're logged in, you already have the cookie, etc., so you should just be directed either to:
1. The dashboard of the only organization you are in, or
2. The organizations page if you are a member of multiple organizations.

**Comment by flipsasser** [comment]
This was fixed awhile back but I just caught one edge case bug and closed the issue with that commit
