### ISSUE TITLE
Users should be removable from an organization without removing from Coyote

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#453]
It's super-unclear right now what happens when "Archive" is pressed on a user. Are they archived for that org or from all of Coyote? If from that org, then can we change this to simply say "remove from org" or something similar. If from all of Coyote, then we need to simply remove this functionality for even owners of organizations, because the only role that should ever people able to archive a user from all of Coyote is a super-admin role (whatever the God role maps to in this app) and then implement "remove from org".

**Comment by flipsasser** [comment]
This was done awhile ago but I didn't know marking it as complete in the project didn't close the issue, too
