### ISSUE TITLE
List of organizations isn't marked up correctly

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#457]
The list of organizations when you are a member of multiple and it asks you to choose one isn't marked up as a UL. This needs to be changed. The UL may also require a heading as well.

**Comment by sinabahram** [comment]
@flipsasser  can you verify this please? I'm talking about the component that lets me select which org I want to be working on. That sure doesn't feel like a table what so ever. It doesn't even have any other links that the org name (no edit or anything), so are we talking about different components?

**Comment by flipsasser** [comment]
Let's get on the same ... **page**, get it? Hoooooo, are my jokes ever terrible.

If you visit https://staging.coyote.pics/organizations, then yes that's a table. In the markup there's room for an "Edit" link if you can edit the org - for some reason it's not rendering for staff members. Probably a permissions error.

**Comment by sinabahram** [comment]
Yes, that is a table. I see that now. ok, so can we A) make a ticket for staff because that is an issue as you described, and B) now that we both agree it is a table, can we remove the fact that there’s an h1 just hanging out but also a caption? The h1 should be the daughter of the caption.

**Comment by flipsasser** [comment]
Forgot to close the issue; this is done
