### ISSUE TITLE
Resources must be deleteable

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#458]
This functionality seems to be missing.

**Comment by flipsasser** [comment]
Added to the UI and the API. Will be ready to review on staging in a few minuts.

**Comment by sinabahram** [comment]
@flipsasser  what's the logic here so we can close this out e.g. If I've got a resource with 5 representations, then I delete that resource, those representations also get deleted? I think that's the cleanest way to go, but there are two suggestions that I think could make htis better.

1: Is there a way to have a list of recently deleted resources/representations (they can be a single entry e.g. I'm not needing a list of deleted resources and deleted representations), just to mitigate against accidental data loss?

2: WordPress and other CMS platforms have a question upon delete that has always resonated with me. They ask if you want to assign the posts of a user to another user when you delete a user. We should also do that, but that should be its own ticket; however, see below.

Could we use that logic from 2 for resources, though e.g. this resource has 5 representations, would you like to assign to another resource?

What's the cleanest solution here while still respecting the fact that folks may have put a ton of time into some representations and hitting a delete button is sometimes all-too-easy. I think we've all been there, so I'm not going to bother explaining the "why" too much more unless if that is needed.

**Comment by flipsasser** [comment]
Right now, it cascades and deletes all representations and assignments. This is the "clean" method in Rails.

I see the use case here, but wonder if re-assigning representations makes sense more than simply implementing a "soft delete" that hides resources from the UI / API, but keeps them persisted and provides a restoration mechanism (more like #1).

**Comment by sinabahram** [comment]
Flip, I agree, so what do you suggest?

**Comment by flipsasser** [comment]
The way I would implement this is:

1. Add a "is_deleted" flag to resources
2. Add an "is_active" scope to resources that filters out resources with "is_deleted = TRUE"
3. Prepend the "is_active" to all actions listing resources or their representations
4. Accept an "is_deleted" filter param in actions listing resources that returns only deleted resources
5. Add a "Trash" link to the resource listing UI that applies the "is_deleted" param appropriately
5. Add a "DELETED" badge in the UI when viewing resources that have been marked as deleted

**Comment by sinabahram** [comment]
That all makes sense, but I thought you did not want to implement soft delete? I thought instead you were advocating for just reassignment if desired, and if not, delete the suckers?

**Comment by flipsasser** [comment]
Sorry I phrased it poorly... I was advocating for soft delete, since I don't understand why you'd move representation under a different resource.

**Comment by sinabahram** [comment]
The reason you’d move it is because there are some related resources and you’re cleaning thins up. This is related to the enhancement request for being able to mark things as duplicates.

 

So, imagine having 5 versions of the same image. Not saying that’s a good thing, but definitely reality.

**Comment by flipsasser** [comment]
What do you think about implementing soft-delete now, and treat marking duplicates as alternative functionality we can build when we need?

**Comment by sinabahram** [comment]
That sounds like a plan, but keep in mind that we should have some ability using the semantic schema stuff to already indicate duplicates, perhaps?

**Comment by flipsasser** [comment]
It is certainly the case that resources cannot be duplicated via source
URI, but "uniqueness" is as fragile as adding a query parameter to the URL

**Comment by sinabahram** [comment]
This is true, but also it speaks to a need for us to potentially not just use URI eventually as a unique identifier.

**Comment by flipsasser** [comment]
Forgot to close the issue; this is done
