### ISSUE TITLE
Descriptions don't cary over on resource assignment

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#460]
Steps to reproduce:
1. Make a resource or choose an unassigned one
2. Add a description
3. Now assign the resource
4. Now notice that the assigned resource's descriptions are not the same as they were when the resource ws unassigned, which is to say they are missing.

It could be argued that this whole flow is a workflow bug and that unassigned resources have no business having descriptions, but then we should close this ticket and make one to prevent unassigned resources from allowing descriptions, as that's currently possible and leads to the above bug.

**Comment by flipsasser** [comment]
Weird, that sounds like a nasty bug. I'll fix.

**Comment by flipsasser** [comment]
I cannot reproduce this. Steps I followed:

1. Select an undescribed, unassigned resource in an org
2. Create a description
3. Return to the resource and assign it to someone else

I still have a table of "Descriptions" containing only the one I added with a status of "Ready to Review"

I'll try again as a different type of user (I'm logged in as staff) and see what happens!

**Comment by sinabahram** [comment]
Hmm, odd. Also try with an assigned resource as well as an approved VS unapproved representation.

 

But if we truly can’t replicate, we can close this out.

**Comment by flipsasser** [comment]
I can't make this happen - is it plausible that you were demoing on staging and I exploded the database mid-demo?

**Comment by sinabahram** [comment]
Quite plausible as this happened a little while ago. Let’s close for now.
