### ISSUE TITLE
API feature: Batch upserts

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#468]
Given a number of source_uris:

```json
[
	"https://d1eujzb03uflva.cloudfront.net/static-pages/james-wines.jpg",
	"https://d1eujzb03uflva.cloudfront.net/static-pages/michael-sorkin.jpg",
	"https://d1eujzb03uflva.cloudfront.net/static-pages/jeannie-gang.jpg",
	"https://d1eujzb03uflva.cloudfront.net/static-pages/Paula.Scher-%C2%ACAlisa.Connan_044_web.jpg",
	"https://d1eujzb03uflva.cloudfront.net/static-pages/behnaz-saraphor.jpg",
	"https://d1eujzb03uflva.cloudfront.net/static-pages/jake-barton.jpg"
]
```

which I `POST` to an endpoint, I would like to get in response:

```json
{
	"https://d1eujzb03uflva.cloudfront.net/static-pages/james-wines.jpg" : 24893,
	"https://d1eujzb03uflva.cloudfront.net/static-pages/michael-sorkin.jpg" : 24894,
	"https://d1eujzb03uflva.cloudfront.net/static-pages/jeannie-gang.jpg" : 24895,
	"https://d1eujzb03uflva.cloudfront.net/static-pages/Paula.Scher-%C2%ACAlisa.Connan_044_web.jpg" : 12345,
	"https://d1eujzb03uflva.cloudfront.net/static-pages/behnaz-saraphor.jpg" : 12889,
	"https://d1eujzb03uflva.cloudfront.net/static-pages/jake-barton.jpg" : 13542
}
```

Where hypothetically the first 3 are resources that were newly created, and the last 3 were already known by coyote.

**Comment by jkva** [comment]
Referencing issue #469 here; ideally I could also provide an existing alt text (if available) which then gets added as resource representation.

**Comment by flipsasser** [comment]
You can post to `/api/v1/resources/create` with a request body of many resources. They will be handled identically to the individual request body you use for `POST /api/v1/organization-id/resources` but should come in a `resources` array, e.g.

```json
{
  resources: [
    {source_uri: "...", representations: [...], name: "This is a great resource"},
    {source_uri: "...", representations: [...], name: "This is another resource"},
  ]
}
```

**Comment by jkva** [comment]
@flipsasser are you sure that url is correct? I'm trying to POST to `https://staging.coyote.pics/api/v1/resources/create` but no dice. 404.

**Comment by jkva** [comment]
@flipsasser when a resource is updated and array data is modified, are the arrays treated as a set union, or are they replaced by the update's version of the array?

**Comment by sinabahram** [comment]
For what it’s worth, I think this should be a set union because otherwise it’s much more work for clients to just update things like Host URIs on a resource e.g. some WP page gets an image added to it, then another one does, etc.

**Comment by flipsasser** [comment]
@jkva @sinabahram I'm not 100% clear on the question, but the general logic is:

1. Look for an organization resource with the given source URI
2. Look for an organization resource with the given canonical ID
3. If it found one or the other, update it
4. If not, create it
5. When appending representations, do not duplicate - if a representation with the same text/language/metum combination exists for that resource, skip it; if one does not, create it

**Comment by sinabahram** [comment]
@FlipSasser, your answer doesn’t touch on hostURIs what-so-ever, though, so I’m not sure how to respond or what to respond to.

 

Let’s start with:

How can Job update hostURIs from WP?

 

Second question, if can be batched (this is really necessary), then is it just a “set union”?

 

We think it should be.

**Comment by flipsasser** [comment]
I misunderstood "array data" to mean "arrays of resources" or "arrays of representations." AFAIK resources don't do anything fancy with host_uris, e.g. they simply replace the old value with the new when given a new value.

Using a set union, how would one go about removing host URIs?

**Comment by sinabahram** [comment]
Flip, exactly, that is now the question we need to answer together.

 

I think removing them is of far less priority than getting them in there, especially if they can be removed from within Coyote’s UI.

 

But, also, would that hostURIs array field not be addressable as a one-off (not batched) through the existing API for delete?

 

Thoughts?

**Comment by flipsasser** [comment]
I modified the API to perform a set union on bulk upserts, but to simply overwrite the field when hitting a resource directly. It should go out shortly.

**Comment by flipsasser** [comment]
Closing this out as @jkva has been using the endpoint. Please open new issues as they come up.
