### ISSUE TITLE
HTTP 422 when resource source_uri already known

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#474]
I'm not sure if this is a bug. Could I get the ID of the known resource instead?

```json
{
  "errors": [
    {
      "title": "Invalid source_uri",
      "detail": "Source uri has already been taken",
      "source": {}
    }
  ],
  "jsonapi": {
    "version": "1.0"
  }
}
```

**Comment by flipsasser** [comment]
Can you confirm this is still happening? I introduced some safeguards to prevent it but it's worth double checking

**Comment by flipsasser** [comment]
I added a regression test to ensure resources would be found by source_uri rather than reject the change as a duplicate. Booyah.
