### ISSUE TITLE
Design Refinements - Remaining Styling Work

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#48]
This is an outline of the "low-hanging fruit" that will get coyote looking more like the design. For all of this please refer to the design sketches added via dropbox link at the bottom.  

First, all views and containers should be white background only.

Most views (list and object)
- [x] B&W styling of check boxes WONTFIX browser standards vary, overly complicated
- [x] B&W styling for dropdowns WONTFIX browser standards vary, overly complicated
- [x] B&W styling of x to remove an assignment
- [x] Remove background highlights, everything white
- [x] Black row lines, single pixel all white background
- [x] Assign on Queue page should be white w/ black outline (secondary button),
- [x] Total numbers next to headers moved to be inline text, E.g. "Total: ####" or "Undescribed Images Queue: ####" (no grey label-like styling, inline the number to the header separated by a semicolon)
- [x] ? all buttons should be this treatment except labels and instances of primary buttons, which are inverse black with white text. I am thinking list views use secondary buttons (EDIT/DELETE) Happy to discuss.
- [x] View/Edit/Delete– use B&W buttons instead of icons , no "view"

Admin view
- [x] Approve/Reject/Edit button styling, use B&W buttons instead of icons
- [x] container for description styling (white background black outline only
- [x] Text styling on author
- [x] ? Style Assign to button (smaller button, white with black outline)
- [x] ? Number of descriptions, black outline, white background, black number 

Page level (description/image)
- [x] Remove info text from interface, this should go on a singular help page
- [x] Style of WYSIWYG editor
- [x] Pages should be labeled “Context”

Design Sketch for reference: 
https://www.dropbox.com/s/gzegi8q7fgp1v8f/14%20coyote%20design%20refinements%20%281%29.pdf?dl=0 
New Description Design sketch next to Live (side by side):
https://www.dropbox.com/s/vpnckpo86d2cepb/Coyote%20design%20-%20mock%20up%20vs%20live%20-%20description%20page%20-%2020160924.jpg?dl=0

Thank you sorry it took a while to do a full assessment. There will be two more posts that will include things that I think we should try to do sooner than later, and then a third with the remaining work to match the design concept that contains greater complexities, such as the switch to a checkbox-based filter viewing on list pages.

**Comment by alavatelliMCA** [comment]
Note that this issue has been updated if only viewing via email, check on github.

**Comment by seeReadCode** [comment]
Thanks @alavatelliMCA!  I'll be looking forward to the remaining two posts.

**Comment by alavatelliMCA** [comment]
Chris it's looking great! Please let me know when checked off items are ready for review.
For instance I noticed there are still colored row highlights on images list view and this item is checked off on the list.

Thanks so much!

**Comment by seeReadCode** [comment]
@alavatelliMCA I think all of the checked items are deployed but I may have missed certain instances of the broader asks because I haven't done a thorough review yet.   Please feel free to add more specific tasks as new checkboxes if you notice them.  Thanks!

**Comment by alavatelliMCA** [comment]
It really is looking so awesome, very exciting. The nitpicking things I noticed are 

B&W styling for dropdowns
- [ ] square corners (list views, new description page)

 Remove background highlights, everything white
- [ ] images list view
- [x] description list view
- [x]  admin view

 Black row lines, single pixel (currently gray) between entries
- [ ] List views
- [ ] Object page (between fields)

Thank you!

**Comment by seeReadCode** [comment]
Square corners isn't trivial for form dropdowns (it's varies by browser and would require a replacement surrogate and a hidden original), cf. http://stackoverflow.com/questions/8927974/css-border-radius-for-the-drop-down-box-when-using-the-select-tag-not-the-sel

**Comment by seeReadCode** [comment]
@alavatelliMCA ok, I think we are ready for a review now.  thanks!

**Comment by alavatelliMCA** [comment]
Looks so fantastic! We love it.

The only thing I notice, is that when a button is unavailable it has a mouse over state, it shouldn't react to mouseover, just be unavailable. See screenshots of the mouseover state:

![screen shot 2016-10-04 at 3 19 09 pm](https://cloud.githubusercontent.com/assets/8040710/19090953/508d585c-8a46-11e6-952c-6a75b877dd70.png)
![screen shot 2016-10-04 at 3 14 40 pm](https://cloud.githubusercontent.com/assets/8040710/19090952/508ca2cc-8a46-11e6-8736-d2fe8bfd2161.png)

**Comment by seeReadCode** [comment]
Ok, I've fixed the disabled hover-over.
