### ISSUE TITLE
Ensure authoring permissions are properly implemented

### ISSUE THREAD

**Issue by flipsasser** [coyote-team/coyote#485]
Authors can describe resources: if they've been assigned
Editors, admins and owners can describe resources: always
Everyone else: cannot describe resources

**Comment by flipsasser** [comment]
#438 should be resolved by this, FYI

**Comment by flipsasser** [comment]
@sinabahram as I dig into this, it's clear that the "author" role was initially much more broadly capable than we are now saying. Authors had the ability to create (but not update, oddly) resources, describe anything, and manage resource links.

In the core resource / representation workflow, the only thing an "editor" role or higher is required for is modifying a representation that does not belong to the user.

I just want to be very careful about modifying author permissions - we are talking about, effectively, stripping them of the ability to do anything that has not been assigned to them. That being said, what do we do about authors creating resources - but not being able to then change those resources?

I wonder if this workflow needs to be rethought with statuses in mind, e.g. an author can create resources and modify them until the resource has representations by different authors? An author can create a representation (if they've been assigned), but can only modify it **before** it is "approved?"

I'd love to hear your thoughts on that before I commit, because this represents a break from what authors previously could do in the system.

**Comment by flipsasser** [comment]
Also - an author creating a resource should potentially also assign the resource to the author for description

**Comment by sinabahram** [comment]
I think authors have too many permissions. I don’t understand why they should be able to create resources. That should be an editor’s job.

**Comment by flipsasser** [comment]
- [ ] Ensure authors cannot create resources
- [ ] Ensure ownership of representations when non-editor level users want to contribute
- [ ] Ensure only authors or higher can create representations

**Comment by flipsasser** [comment]
Marked this as done but I guess it didn't close the issue. This is all implemented and tested
