### ISSUE TITLE
Querying unknown resource ID results in HTTP 500

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#487]
Example: `GET https://staging.coyote.pics/api/v1/resources/342181111` results in HTTP 500 while `GET https://staging.coyote.pics/api/v1/resources/34213` works.

**Comment by flipsasser** [comment]
Whoops, didn't mean for the commit to close until we could test in staging. This should be fixed but let's wait to test live.

**Comment by flipsasser** [comment]
This is fixed and deployed - we can reopen if it happens again
