### ISSUE TITLE
UI tweaks for search and indexes

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#49]
These are some modifications to improve usability while not going all the way with the design proposal, still working with the current functionality set and table view.

Tweaks to improve UI
- [x] Use SEARCH/CLEAR buttons instead of icons below dropdown/search field block, currently magnifying glass and x
- [x] Change thumbs up/thumbs down to APPROVE/REJECT buttons same as on admin page, white background black text (vertically stacked to keep column narrow) checkbox above this for selecting all
- [ ] Move dropdown and Field searches to the left of the table, this helps to keep content of dropdown from being cut off by column width
- [ ] Instead of underline on column header small arrow to indicate sort

If not a crazy ask at this phase to get us closer to the design proposal:
- [ ] Adjust Columns to double row hight on images in order to compact data into two rows to be able to reveal full description or caption on image view.
- [ ] Description view order of fields top row: Image, Status, Metum, Locale, Author; second row description (text), edit/delete
- [ ] Image view order of fields top row: Image, Priority, Status, Metum, Group, Tags, Date; second row caption, edit/delete (only admins can edit images)
- [ ] auto size box for writing text larger, or make default size larger?
![screen shot 2016-10-21 at 4 26 20 pm](https://cloud.githubusercontent.com/assets/8040710/20080151/b530e698-a50d-11e6-9b17-fd55fb9308b2.png)

**Comment by alavatelliMCA** [comment]
I have updated this issue with a couple tweaks after posting if you are working via email.

**Comment by seeReadCode** [comment]
Moving the dropdown and field searches to the left will break some screen reader navigation (via `<th>`).  @sinabahram please confirm on this one.

Re: adjusting image columns to double row height and the double row layout, this also has negative implications for the screen reader based navigation & we are showing full descriptions now anyway (with wrapping).  @sinabahram and @alavatelliMCA please confirm on this one.

**Comment by sinabahram** [comment]
I definitely think we should show the whole thing, not just two lines.

 

Let’s chat via voice, though, about the moving the drop downs issue. I think we can still make that work via programmatic association.

**Comment by alavatelliMCA** [comment]
Would be glad to be on a call, tomorrow I am booked up 11:30-2:00 tomorrow. Will be on skype when at my desk if you want to give me a poke.

**Comment by sinabahram** [comment]
I think the call only requires Chris and I re accessibility.

**Comment by seeReadCode** [comment]
I've made some tweaks to improve visibility on the tables but I'm going to hold off on the rest of this list for the time being pending further discussion.

**Comment by seeReadCode** [comment]
Other concepts
- [ ] Relayout queue after assignment (or other "completion" action)
- [ ] Load more button for queues

**Comment by alavatelliMCA** [comment]
Hi all, with MCN fast-approaching I'd be happy to get on a call to talk about how to make the discovery mechanisms at the tops of the columns more user-friendly, we had proposed moving that whole top row to the left of the listing so that we can reveal more usable search box fields, in the current layout the tags search is only 2 characters wide.

**Comment by seeReadCode** [comment]
This change would have some ramifications for accessibility which is my main blocker on this. @sinabahram can we pull the search form out of the table? 

Also, these are the layouts you referring to, @alavatelliMCA , right?

![images index split layout from tobey](https://cloud.githubusercontent.com/assets/8710696/19573038/8dd2199e-96d2-11e6-9096-32d6d2484940.png)
![descriptions index split layout from tobey](https://cloud.githubusercontent.com/assets/8710696/19573042/8f933f88-96d2-11e6-88d2-d77d2c42a37f.png)

**Comment by alavatelliMCA** [comment]
Chris, yes these are the correct sketches. In effort to simplify your workflow and meet accessibility performance expectations I am up for proposed alternatives. I had imagined simply maintianing the sort at the column headers and moving the search because you cannot see what you are typing into the field. when it is limited by column width. As a compromise to get the usability improved while working toward our ideal design. Perhaps it is just separating search out to above the table?

best,
A

**Comment by seeReadCode** [comment]
Thanks!  

I'm not advocating for and don't mean to be asking whether we move the sort functionality or the headers: the input fields for the search form are set in an HTML table in part so that they can be accessed easily by screenreader (which causes the readability issues mentioned on smaller screens).

I don't have a decent quick alternative here (other than suggest everyone get larger screens :) ) because we simply have a lot of columns.

**Comment by sinabahram** [comment]
Let’s talk through it on a call between Chris and Sina RE accessibility. I think this is possible.
