### ISSUE TITLE
Allow users to mark resources as duplicates of other resources

### ISSUE THREAD

**Issue by flipsasser** [coyote-team/coyote#493]
This would merge the two resources' representations and other metadata, and delete the duplicate from the system. Requested as an offshoot of #458

**Comment by sinabahram** [comment]
I'm not sure we can delete one of the resources because the sending client e.g. WordPress or Coyote Client may not know it's a duplicate, so wouldn't they just re-add it back?

**Comment by flipsasser** [comment]
Duplicate of #456
