### ISSUE TITLE
Author role is unable to author descriptions

### ISSUE THREAD

**Issue by 4-x** [coyote-team/coyote#499]
As of sometime in the past 2 weeks, MCA Chicago users with the role "Author" no longer have the option to describe. There is no "Describe" link on the resource page. This is an urgent issue, as it renders the app largely unusable.

![image0](https://user-images.githubusercontent.com/25802672/86260689-3a36c800-bb83-11ea-9312-6a61e016399c.png)

**Comment by 4-x** [comment]
Is there a fix being considered for this? Our authors are unable to write any descriptions until it has been resolved.

**Comment by flipsasser** [comment]
@4-x this is the result of #485, which was to resolve an issue w/authoring permissions that were too loose. **Authors now need to be assigned a resource before they're able to describe it.**

The "editor" role is able to describe any resource in the system.

**Comment by sinabahram** [comment]
@4-x  if the authors have the resources assigned to them, then they can describe them. The other way worked before (authors describing unassigned resources), but that was the actual bug. This is now behaving per the design intent of the platform.
