### ISSUE TITLE
MCA collection captions not getting pulled by MCA

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#50]
I am posting in case y'all have good ideas around this, as it will be a common issue for collections websites.

http://coyote.mcachicago.org/images/12369
https://mcachicago.org/Collection/Items/Buckminster-Fuller-Inventions-Twelve-Around-One-1981-27
The caption isn't being pulled on collection objects. 

I am checking with Tomas to see how we can get caption information from collection objects tied to the image. The trick is that captions are coming from a different source than the image and populating together on the collection object page. Fortunately context allows us to quickly see that information so it is easy enough to work around, but renders collection images un-searchable in coyote.

Thanks
A

**Comment by seeReadCode** [comment]
@alavatelliMCA any word from tomas on this?  I can build out some logic to allow individual title checks.  In this case it looks like the caption is still missing:

https://mcachicago.org/api/v1/attachment_images/57e684797a1daa13e900015d.json

**Comment by alavatelliMCA** [comment]
You know this pointed out to me that there is no way for me to find this image on coyote, because I can only search captions, titles, descriptions and tags. Meaning I can't find it in its original web context to identify why it might not have a caption.

We have a rather large deployment pending with a bunch of very needed (unrelated) fixes so we haven't been able to get into sorting this out on his end. I think it has to do with the central asset repository, and people potentially uploading content without adding caption content.

**Comment by sinabahram** [comment]
Just to be clear. Is there a proposed ask here, Anna, or just an observation?

**Comment by seeReadCode** [comment]
This isn't a bug with Coyote so I'm removing the label for now.

**Comment by alavatelliMCA** [comment]
Observation and update on situation.

**Comment by seeReadCode** [comment]
@alavatelliMCA this issue is effectively an issue with MCA rather than Coyote.  Can we close it?

**Comment by alavatelliMCA** [comment]
Well, one of the reasons I flagged this issue is that it is common for the asset to be separated from the caption on collection websites as the data is pulled from two different sources, a collections management system and a digital asset management system. So this could be a many museum issue affecting public instance, or future installs, not just an MCA issue.

I am making an inquiry with Tomas about how this caption data could be linked with the asset to resolve the MCA issue.

**Comment by seeReadCode** [comment]
Understood. 

I think we should pursue this broader design conversation.  I thought to add the latest timestamp on the home page as a result of this issue.  But I wince every time I look at the issue list and see the title of this issue and then I remember that it's not really an active issue for me.  I'll alter the title to clarify.

**Comment by seeReadCode** [comment]
@alavatelliMCA are these collection captions coming thru now?

**Comment by alavatelliMCA** [comment]
Tomas is to fix on our end.
