### ISSUE TITLE
User management via API

### ISSUE THREAD

**Issue by 4-x** [coyote-team/coyote#501]
It may be a useful feature for users to be managed via the API. If this functionality already exists, it is not included in [the API documentation](https://coyote-team.github.io/coyote/api/).

**Comment by sinabahram** [comment]
I believe what you're asking for is for the API to facilitate adding/deleting users, correct? If so, I think this is a great enhancement request, and I've marked it as such.

**Comment by flipsasser** [comment]
This is done! Read up on it here: https://staging.coyote.pics/apidoc/1.0/memberships.html
