### ISSUE TITLE
Owner role does not have maximum privileges

### ISSUE THREAD

**Issue by 4-x** [coyote-team/coyote#503]
A user with owner role permissions cannot edit other owner role level users.

**Comment by sinabahram** [comment]
This has bugged me for a while, so it's time to make a decision on it. Here is what I propose @flipsasser: 

1. Owners should be able to add/remove owners as well as any other role.

2. Admins; however, should only be able to add/remove other roles below them e.g. editor, author, etc..

3. Editors and below per my comment on #504  should not have any membership editing at all.

**Comment by flipsasser** [comment]
- [ ] Allow owners to manage all members
- [ ] Ensure admins are only able to manage membership levels **below** admin
- [ ] Ensure editors are not able to edit memberships; only view

@sinabahram just for clarity, admins cannot add or remove other admins?

**Comment by flipsasser** [comment]
This is changed and deployed to production
