### ISSUE TITLE
Restrict member list access by user role

### ISSUE THREAD

**Issue by 4-x** [coyote-team/coyote#504]
Author role users can currently view the complete member list with associated emails. As we are inviting more outside users to write descriptions, we may prefer to limit this access to users at the Editor level or higher.

**Comment by sinabahram** [comment]
I agree. This honestly feels more appropriate for admin, not even editors. @flipsasser  can we simply not show members to editors and below? Assigning to you.

**Comment by flipsasser** [comment]
Yup, that's a simple permissions switch. I'll "flip" it.

**Comment by flipsasser** [comment]
This is done
