### ISSUE TITLE
Merge users

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#51]
![screen shot 2016-10-18 at 11 15 44 am](https://cloud.githubusercontent.com/assets/8040710/19486488/4006fea0-9524-11e6-8f94-cb2b98f5e8d6.png)

Is there any way that we can the two Sheila Majumdar accounts be merged as an Admin account under her MCA email easily?

If not we'll figure something out.

**Comment by sinabahram** [comment]
As a “one-time” thing, this may be able to be done, but as a feature, I’ll claim it’s totally out of scope for now.

**Comment by alavatelliMCA** [comment]
Totally fair, shouldn't be a feature. If at all complicated I can just kill her non-mca account.

**Comment by seeReadCode** [comment]
I can do this as a one time fix.  I'll post you when it's fixed.

**Comment by seeReadCode** [comment]
Done: http://coyote.mcachicago.org/admin/users/5
