### ISSUE TITLE
Double check that webhooks fire for every resource group

### ISSUE THREAD

**Issue by flipsasser** [coyote-team/coyote#511]

**Comment by flipsasser** [comment]
@jkva which organization are you testing with? I see multiple `ch-dev-{n}` orgs, but none that have more than one resource group with a webhook

**Comment by sinabahram** [comment]
Out of caution, we weren't trying that anymore because we're concentrating on finalizing the WP client. Happy to add it to the list of things we try next week e.g. I'll make a Wordpress group and then put the callback in there instead of on default.

**Comment by flipsasser** [comment]
I'm going to close this, as last I heard this was working as expected
