### ISSUE TITLE
Dropdown for assignments

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#52]
![screen shot 2016-10-18 at 11 21 12 am](https://cloud.githubusercontent.com/assets/8040710/19486766/4a1760aa-9525-11e6-9f10-af281d57e261.png)

There is an overlap, but the order is making it hard to find names of people to assign, appears to be  by creation date? Could it be alpha?

**Comment by seeReadCode** [comment]
Sort is by last name alpha

**Comment by seeReadCode** [comment]
I'll fix the overlap (z-index) bug soon
