### ISSUE TITLE
Enhance search to operate on Resource Groups

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#528]
@flipsasser , let's use this as an excuse to have the overdue larger conversation about filters/search that we've been wanting to have.

**Comment by flipsasser** [comment]
@sinabahram I went ahead and implemented this per the discussion we had about accessibility in the filters / search sections of representations and resources. I'm still working on getting mobile styling to "auto" collapse the filtering UI and the bulk edits UI, but hopefully we're close to the changes we discussed

**Comment by flipsasser** [comment]
Donezeo
