### ISSUE TITLE
Bulk assignment of Resources to a Resource Group

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#529]
This is operationally related to #528, but different from a development sense. Let's make sure that as we make Resource Groups first class models within Coyote, bulk assignment also can be done on Resources to assign them to a Resource Group.

@flipsasser, please note: no need to try to implement multiselect here. If someone wants to bulk assign to multiple Resource Groups, it's ok to make them do that as two or more individual bulk assignments.

**Comment by flipsasser** [comment]
This is in the latest UI batch
