### ISSUE TITLE
Editable Footer Text

### ISSUE THREAD

**Issue by ruthestarr** [coyote-team/coyote#531]
Footer text should be editable scoped to an organization for users with owner level permissions

**Comment by flipsasser** [comment]
This has been done for some time! When you edit an organization, there is a field for "Footer notes" that will override the default footer content

**Comment by annachiaretta** [comment]
Just to nitpick, maybe the field should simply be labeled Footer (notes sounds like something for backend ui only).

**Comment by sinabahram** [comment]
@annachiaretta  sorry, I don't get your comment. It is called that.

**Comment by annachiaretta** [comment]
Hmm, what I'm seeing is a field label of "Footer notes" 
"Footer" would make it clear this is the user facing footer content.

**Comment by sinabahram** [comment]
I get it. You just want the word "notes" gone, yes?

No problem at all. @flipsasser  can you make that modification please on the next push?
