### ISSUE TITLE
Increase margins on import/view resource buttons

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#533]
Underneath the Import Resources and New Resource buttons, we need to add some space before the horizontal line so that it isn't touching the buttons like it is now.

**Comment by flipsasser** [comment]
I have a TODO item to fix this along with some accessibility stuff we reviewed about those buttons, @sinabahram. Will fast track that today

**Comment by flipsasser** [comment]
This is deploying with a whole slate of other fixes now
