### ISSUE TITLE
Resource upload auto-creates Source URI / Remove option to upload

### ISSUE THREAD

**Issue by annachiaretta** [coyote-team/coyote#539]
When uploading a resource to Coyote the form should fill in the Source URI with the upload's destination. 

I'd also like to unpack this feature: I'd be curious of the use-case for resource upload outside of kicking the tires on the system, what purpose does this serve if Coyote is to always live in the networked environment? Particularly as it could result in unnecessary consumption of server space (inadvertent use of coyote as a DAM by a user) as well as the potential future disconnect between assets in the online space and those uploaded to Coyote.

**Comment by annachiaretta** [comment]
The other option here is to simply remove the option to upload resources (probably a good idea since we don't want to be an asset repository) and update help text to explain the Source URI:

`Add an image by copying the URL or source URI. Use the address of the image file itself that identifies the canonical location of the resource.`

**Comment by flipsasser** [comment]
This has been removed
