### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#54]
A user just tried to reset there password and are getting a Server Error

(server encountered a temporary error...)

Do you need anything from us, like our mandrill account?

**Comment by alavatelliMCA** [comment]
Update - still waiting on a response from MCA helpdesk on SMTP account set up for sending.

**Comment by seeReadCode** [comment]
@alavatelliMCA any word from the help desk?

**Comment by alavatelliMCA** [comment]
I will follow up with them, there is a significant delay in responses to non-emergencies as MCA offices have been renovated and reorganized throughout the museum over the past few weeks and continuing through the next few. So they have a ton on their plate.

**Comment by alavatelliMCA** [comment]
The account is set up as SMTP, so assuming it was working before the only reason it wouldn't is if there is a change on your end.

**Comment by seeReadCode** [comment]
I still can't get these creds to work and the webmail page still says the account is not setup for SMTP.  I deployed with a coyote.daemon@gmail.com account that I created yesterday just so we could have password reset work and tested and it's working.  I'm closing this issue for now.  Please let me know if you get a working SMTP email creds for me or can get me on the phone with your IT/email folks, we can get this workin

**Comment by alavatelliMCA** [comment]
Thank you for the workaround solution. If still desired to have a call with IT please let me know and I'll set up.

In the meanwhile we have a new problem with password reset, After resetting the password my users are getting cued to login screen with a red error message that reads:
`You need to sign in or sign up before continuing`

as shown here:
![screen shot 2016-12-20 at 10 00 00 am](https://cloud.githubusercontent.com/assets/8040710/21357542/22b8d8ca-c69b-11e6-81b5-774700d653ca.png)

**Comment by seeReadCode** [comment]
@alavatelliMCA If the password reset email is being sent, the status message here is not in fact inaccurate: the user will need to finish creating a new password via the email before continuing.  If you'd like the message hidden in this instance, that could be done.

No need for the IT call.

**Comment by alavatelliMCA** [comment]
Ah, I see. I think the message threw everyone off as there is nothing that says they successfully reset their password, I failed to follow through and ask if their new password indeed did work.

However, hopefully you can see something on the backend, for SSkalitzky@mcachicago the password reset is not working. I just sat next to her watching her reset it twice and it definitely doesn't seem to register her new password.

I am certain if there is nothing in their email nor on the screen that lets users know that they successfully reset their password I will get a phone call every time. If simple and easy enough to hide the error message I think this is a VERY good idea.

And as always thank you for the super quick response.

**Comment by seeReadCode** [comment]
@alavatelliMCA there was in fact a bug here: the form was being submitted to the wrong endpoint.  Not sure how that got past me in October but in any case it's fixed now (both the underlying issue and the message).  The user should now be logged in after they submit their new password.
