### ISSUE TITLE
Resource Group Enhancements

### ISSUE THREAD

**Issue by annachiaretta** [coyote-team/coyote#543]
(feel free to break out into separate issues)

1. Make webhook URI only visible to admins and owners (I would also argue that help text or link to documentation on webhook URIs and how to use them for this feature of Coyote would be ideal)
2. Make a webaim contrast compliant color picker for group labels, with a default of light gray (pastel colors would ensure proper contrast with dark text)

**Comment by sinabahram** [comment]
Closing this in favor of #544  and #545
