### ISSUE TITLE
Coyote interface enhancements: color and style

### ISSUE THREAD

**Issue by annachiaretta** [coyote-team/coyote#544]
I found that many colors used on buttons are not fully contrast compliant according to the [WebAIM contrast checker](https://webaim.org/resources/contrastchecker). Furthermore as the focus is on describing images, the colors interfere and distract from the images, especially on dashboard views I suggest a refinement of the use of color on the interface. 

I am suggesting 3 main action button related styles to reduce the rainbow effect of the orange/blue/red/purple/green (note these colors are darker versions of colors used currently to be AAA compliant). I put together a spreadsheet analysis of buttons and labels throughout the site with the recommended changes on [google sheets](https://docs.google.com/spreadsheets/d/1DutFRkp827obP4ueYIYWeB_nzIXUhIdiNZEeYx1sPJA/edit#gid=0). Below is an overview:

- white text `FFFFF` on dark gray `595959` (used for assigning, linking, searching, and other peripheral interface actions-mostly as used currently)
- outline style: as seen on the cancel and delete buttons in some layouts, the following is a screenshot of the cancel button on the description submission form page. (all interface actions besides approving in the general workflow). <img width="98" alt="Screenshot of cancel button in current coyote ui" src="https://user-images.githubusercontent.com/10015955/109177028-637d1780-7755-11eb-8e9b-2f189cb8f6af.png">
- white text `FFFFF` on dark blue `2B5D79` (used for checkboxes, and admin actions: approving, adding, importing; as well as page level creation, updating actions - core actions that advance descriptions through the workflow)

The fake-black (dark gray) should be darkened to 595959 throughout, also note that the contrast of this gray is [technically fails AAA compliance](https://webaim.org/resources/contrastchecker/?fcolor=595959&bcolor=FAFAFA) with the current off-white `FAFAFA` background, we will gain better contrast if we use full white background, which I recommend.

And a note about visual style: Personally I prefer square edged buttons and interface elements because I think it is a more contemporary design approach and is being seen in a lot more in mainstream tools (e.g. Mailchimp and Dropbox). However, as I understand that as Google and Apple dominate our understanding of an "undesigned" interface and they do rounded edges on everything, I defer to the wider group's preference.

**Comment by flipsasser** [comment]
Thanks! There was an algorithm to keep it WCAG AAA compliant but I don't think it worked. I removed most of the calls to it but I'll go through again and take this advice into account

**Comment by flipsasser** [comment]
I'm going to close this out - I tried to hew close to these suggestions while opting for using the "brand" color as the primary driver here. We can always revisit once you've had time with the new system

**Comment by sinabahram** [comment]
Now that the UI pushes that were already in flight have been pushed, along with several feature enhancement and bug fixes, I want to reopen this issue in order to explore if there are remaining usability concerns with what is on staging.

**Comment by flipsasser** [comment]
Sounds good! In the future, would it be possible to open specific tickets
rather than large omnibus ones and link them against this one?

**Comment by annachiaretta** [comment]
Solely for future reference I am sharing the original pdf file of the Coyote interface guidelines designed by Tobey Albright. I realize at this point we've gone in a different direction, but want to get this captured here in case we ever want to return to this down the road, it is also interesting to look at after so much time!

I think it represents a visual trend that has bubbled up to a lot of mainstream interfaces (Dropbox, Mailchimp, Squarespace, GoDaddy's recent rebrand)  and I wouldn't doubt that accessibility has an influence in this style becoming more acceptable,  it is highly accessible approach as you avoid the contrast loss that comes with the previous trend of softening of the look and feel by using what I call fake black and fake white. (It's also an example of the classic trend: designers and artists do "crazy" gestures that are "ugly" or break with established "rules" and then they get absorbed into the mainstream.)

Thank you for indulging me! An archivist by nature I stumbled into it cleaning old drives:
[14 coyote design refinements.pdf](https://github.com/coyote-team/coyote/files/6222085/14.coyote.design.refinements.pdf)

**Comment by sinabahram** [comment]
Thanks for this. Just noting this is already captured in the repository, but good to have it here as well.

Also, we should talk about the use of all-caps (not sure if that is prescribed in the designs). We need to start removing it from Coyote since it destroys word shape.

**Comment by flipsasser** [comment]
Implemented this per the feedback from @annachiaretta
