### ISSUE TITLE
De-couple states of descriptions and resources

### ISSUE THREAD

**Issue by annachiaretta** [coyote-team/coyote#547]
Below is a proposed decoupling to break out the status into specific fields. For descriptions this might mean no change, but want to capture a comprehensive overview of status in this issue to ensure we haven't overlooked a UI complication this could create. This will inform an updated approach to filters on list views and is also supporting the deep think in progress on the dashboard.

### Description state

Description Status

- Ready To Review
- Approved 
- Not Approved

### Resource states

Resource Status

- Represented
- Unrepresented
  

Assignment Status

- Assigned
- Unassigned
  

Progress 

- Described (this state does not display on resources, intentional?)
- Pending (contains descriptions that are unapproved), this is a suggested additional state
- Partially Completed (**only an approved metum counts** toward this state, required defined by admin/owner)
- Undescribed

**Comment by sinabahram** [comment]
Anna, thanks so much for writing this up.

@flipsasser  what are your thoughts here on the backend? Is this one enum or two enums right now or actually already phrased individually on backend? Decoupling and such should be straight forward (famous last words said by the guy not writing the Ruby, I know!).

I suggest complete 100% consensus amongst the four folks I've assigned to this issue e.g. Sina, Anna, Ruth, and Flip, before we move forward.

Looking forward to discussing it. If we nail this, folks, it'll drastically simplify the data model and the UI, I feel.

**Comment by flipsasser** [comment]
Notes:

Resource status
- Represented: has at least one representation for all required meta, and one meta is always required
- Unrepresented: does not meet "represented" criteria

Other inferred statuses: move them into cached statuses

Dashboard UI: admin vs. editor

**Comment by flipsasser** [comment]
This is done and on staging and apparently popular
