### ISSUE TITLE
Regular users - Descriptions at 0 and can't describe

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#55]
From a new regular user:
I went to go add the longer style description to the Susanne Simpson, still from Karl Wirsum, but it bounces me to that same empty description page.

![screen shot 2016-10-21 at 4 24 34 pm](https://cloud.githubusercontent.com/assets/8040710/19612457/4aa3eae6-97ac-11e6-9b46-2f8d764e4856.png)

**Comment by seeReadCode** [comment]
This is as designed. A non-admin user can only describe images that they have been assigned.

**Comment by alavatelliMCA** [comment]
I guess we didn't realize this was how it was designed. 
This explains some of the hold up in descriptions as the admin team is small and not always able to keep up with assignments. Users should always be free to describe as they wish, activity should not be limited, we maintain a moderation layer so there is no harm in collecting more descriptions.

The expectation is the following:

1. Users can describe any image
To ensure that 
2. Users can see all approved descriptions
This is important for those new to describing to learn from those descriptions that have been approved.
3. (Enhancement) - below queue list undescribed recently added images or link to images list view

**Comment by seeReadCode** [comment]
addressed in 2f52a9 and 5ade5b9

**Comment by seeReadCode** [comment]
@alavatelliMCA  please close if you are happy with this implementation for now and move future enhancements out to a separate issue.

**Comment by alavatelliMCA** [comment]
Any future enhancements will go into backlog or a separate issue. Thank you!
