### ISSUE TITLE
Description List view adjustments

### ISSUE THREAD

**Issue by annachiaretta** [coyote-team/coyote#550]
To improve usability I suggest the following changes:

1. Remove Delete action (I argue no descriptions should be deleted, it doesn't appear at the page level, but if we want to keep it as an option I think page level would be the place)
2. Add Approve and Reject actions to list view: So that it is View Edit Approve Reject

**Comment by sinabahram** [comment]
Agreed on these. Delete is not common enough to deserve primacy. Given the actions list growing, should that be a drop down menu instead of four items to conserve UI space?

**Comment by annachiaretta** [comment]
I would rather remove Reject from the top level actions if we have to lose something.
That said, I think space allows, especially if we stacked buttons View Edit above Approve Reject as a 2 row situation.

**Comment by flipsasser** [comment]
Got it - added to https://github.com/coyote-team/coyote/projects/6

**Comment by flipsasser** [comment]
Happy to close this out!
