### ISSUE TITLE
UI does not show multiple resource groups the resource belongs to

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#554]
![A resource showing to belong to resource group "Uncategorized" and "WordPress"](https://user-images.githubusercontent.com/217264/109712193-05f72980-7ba0-11eb-9ff5-4a18d57befc5.png)

![A resource showing only one resource group in its list of resource group memberships](https://user-images.githubusercontent.com/217264/109712270-1d361700-7ba0-11eb-8eba-61fbab6d4b38.png)

**Comment by flipsasser** [comment]
This is fixed
