### ISSUE TITLE
when moving a resource into a resource group, URL validation fails due to missing protocol specifier

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#563]
Maybe a resource group validation thing after you, @flipsasser, made things protocol independent, but now adding a resource to a group results in Coyote complaining about the missing http.

Happy to provide more info if you can't reproduce, but just try adding a resource to a group on production.

Can we set up a test for this to catch it if it ever regresses?

**Comment by flipsasser** [comment]
HTML validation on the URL field needs to get pulled

**Comment by flipsasser** [comment]
Fixed! Will be out momentarily
