### ISSUE TITLE
Surface assignment status of resources more prominently

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#564]
This may be fixed by the upcoming UI changes, @flipsasser  and @annachiaretta,  but an issue raised by some users is that it's hard to tell the assignment status of resources from just glancing at the resources listing.

Possibly also related to #547

**Comment by flipsasser** [comment]
I added this to the resource listing but the last thing on my plate right now is breaking the statuses up more clearly, and I'd like to keep this open to keep track of it while I wrap that up

**Comment by flipsasser** [comment]
Okay finally closing this out, as this got its own column on resource listings
