### ISSUE TITLE
Automatic Resource Groups

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#565]
@flipsasser  I think this is an example of a really easy feature to add that is incredibly powerful for the long-term usability of Coyote. Let me know any thoughts, but I'd love to push this out much sooner rather than later.

The problem is that users will have tens of thousands of images after a Word Press import. That's great, but lack of categorization is really disheartening because you're just looking at this back log of 12K undescribed resources.

So, what if Coyote could magically sort them for you into resource groups?

Note, obviously they would all also stay within the WordPress resource group because of its callback URL being critical to fire to sync with the WP instance

The answer is that many systems, including WP, have predictable URL patterns, so I propose the following. Thanks go to @NolanHill  for help on the ideation of this feature.

#### Automatic Resource Groups

1. Only can be created/modified by admins or owners
2. Will take two fields, A) a pattern (eventually, we will need a regular expression), but  for now, text matching will do), and B) a dropdown to select which existing group to assign to automatically when the pattern matches. This pattern will match against Host URL of course. That way, we can auto-sort many WP resources. These need to allow more than one pattern to match against the same group. Whatever is easier, either multiple in one or multiple entries is fine with me.

If we had this feature, here is live data you can test with right now on the public CH site which is already set up in Coyote.

#### 7  Auto Groups for Now
1. Blog Posts: ```https://www.cooperhewitt.org/<yyyy>/<mm>/<dd>/<post-title>/```
2. Education:
```
https://www.cooperhewitt.org/education/<page-title>/
https://www.cooperhewitt.org/national-design-awards/<page-title>/
https://www.cooperhewitt.org/national-design-month/
```
3. Events: ```https://www.cooperhewitt.org/event/<event-title-and-date>/```
4. Home page: ```https://www.cooperhewitt.org/```
5. Digital mansion: ```https://www.cooperhewitt.org/digital-mansion/```
6. Exhibitions ```https://www.cooperhewitt.org/channel/<exhibition-title>/```
7. Publications: ```https://www.cooperhewitt.org/publications/<publication-title>/```

This doesn't have to happen at import. I'm thinking a perfect sidekick job. This can help even with static websites, other systems, etc.

**Comment by flipsasser** [comment]
This is up on staging - had a nasty diversion from the design update branches. I'll test on staging once it goes up.

I want to note that features like that this, that lean heavily on Sidekiq, really push us towards finding a hosting provider with **actual** support for background workers instead of the weird workarounds we're using w/Cloudtasker. I really want to start down that path sooner than later!

**Comment by flipsasser** [comment]
Holy cow, it worked on the first try with zero configuration: https://staging.coyote.pics/organizations/60-cooper-hewitt-semipermanent/resource_groups/6700

It automatically linked to 253 resources. I'm going to try removing the auto-link URI to make sure it's unlinking with auto-linked resources when the URI no longer matches

**Comment by flipsasser** [comment]
Yup it's working super well. Okay I'm real happy with that.

Only piece I need to change is where we sanitize the URLs admins enter, and we'll be good to go.

**Comment by sinabahram** [comment]
This is so exciting!

One thing, it seems to be taking away from other groups?

WordPress only has 11.xK rsources but there are 12.xK total resources, and all resources are from WordPress, so WP group must always match total resources, until we start stuffing collections objects in.

Can we figure that out?

**Comment by flipsasser** [comment]
Yup, let me give a look

**Comment by flipsasser** [comment]
This is working on staging and also apparently popular. Very gratifying!
