### ISSUE TITLE
Authors should be able to assign themselves a resourceAuthors Assigning Themselves

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#566]
Sorry to bring this up again but in a democratic world where authors can assign what they want, and Coyote just auto-assigns them when they submit a description, we have not solved for the use case of letting colleagues know you have claimed an image to work on.

Is it at all possible to let authors assign an image only to themselves?

**Comment by flipsasser** [comment]
I extended the policy to support this so users can self-assign - instead of a dropdown of users, the UI just adds a button "Assign to me"
