### ISSUE TITLE
A few images not populating on coyote

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#57]
There are a few images I have been unable to find in Coyote, and they don't offer the usual link back to coyote from the website either.

Examples:
1.
https://mcachicago.org/Calendar/2016/11/Members-Double-Discount-Days
https://static.mcachicago.org/media/images/W1siZiIsIjU3ZjNkNDgzN2QzZTc3NjY4ODAwMDIwNyJdXQ/Ebony_Gold-Leaf_Neck.jpg?sha=e093a391b4d2315c
Caption (when any word searched on coyote image doesn't appear):
`[Ebony, Gold Leaf, and Leather Necklace](https://www.mcachicagostore.org/shop/ebony-gold-leaf-and-leather-necklace-49869)  $960 (Members’ Double Discount price $768)`
uploaded 17 days ago

2.
https://mcachicago.org/Stories/Blog/2016/10/The-Geometry-Of-Thinking
https://static.mcachicago.org/media/images/W1siZiIsIjU4MDhlMWJmYzEyMWY1NzRjYzAwN2MwMCJdXQ/10_LastFrame_1979_NewDims_Opening.jpg?sha=77cafc2e7fd84bca
caption reads:
`FRAME 10: On roll documenting the exhibition opening _New Dimensions: Volume and Space_, MCA Chicago, Mar 10–20, 1979`
uploaded a day ago

3.
https://mcachicago.org/Stories/Blog/2016/09/Unpacking-Concrete-Traffic
https://static.mcachicago.org/media/images/W1siZiIsIjU3ZWQ1NWM5N2QzZTc3NWQ0ZjAwMDRkNCJdXQ/Concrete%20Traffic%20photo%205-1.jpg?sha=56fb91f6ee2b8370
caption reads: 
`The Cadillac in the parking lot shortly before the pour, Jan 1970. Photo: David H. Katzive. © MCA Chicago.`

Also this one has a coyote alt description in the website (that procures 0 results): 
Black-and-white image of a 1957 Cadillac encased in rebar and surrounded by snow

Let me know what parts of this I should flag Tomas on.

**Comment by seeReadCode** [comment]
@alavatelliMCA I ran the updater back across these dates and these got uploaded.  I'm not sure what caused them to get missed.  Let's keep an eye on new images coming into the system over the next week to see if any other similar issues come up.

Here are these:
1. http://coyote.mcachicago.org/images/12569
2. http://coyote.mcachicago.org/images/12561
3. http://coyote.mcachicago.org/images/12591
