### ISSUE TITLE
Apply button overlaps table on resources page

### ISSUE THREAD

**Issue by ruthestarr** [coyote-team/coyote#570]
See screenshot 

<img width="1161" alt="screenshot of resources page showing the apply button overlapping the assignment heading in the table of resources" src="https://user-images.githubusercontent.com/53842927/112079521-b11f5100-8b56-11eb-9185-700efc953c49.png">

**Comment by flipsasser** [comment]
Oops, that's a regression - this is fixed now!

**Comment by flipsasser** [comment]
This was fixed but not closed because whoops
