### ISSUE TITLE
Filter on resources page broken

### ISSUE THREAD

**Issue by ruthestarr** [coyote-team/coyote#571]
Steps to reproduce:

1. Click filter > filter window will pop up on the right-hand side of the page
2. Scroll down with two fingers on track pad 
<img width="1129" alt="screen shot of coyote shows resources page with filter menu on the right" src="https://user-images.githubusercontent.com/53842927/112080150-d52f6200-8b57-11eb-9959-926551bb5450.png">

**Comment by flipsasser** [comment]
A fix for this is deploying to staging now. Please let me know what you think!

**Comment by flipsasser** [comment]
Closing this out as the feedback has been positive
