### ISSUE TITLE
Dashboard scrolls horizontally

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#573]
It seems to have to do with the title not wrapping in some cases when it's a long filename. Perhaps cap it at a maximum number of characters and have it display in its entirety in the detailed view?

![A screenshot of the Coyote dashboard showing a visual cutoff at the far-right side.](https://user-images.githubusercontent.com/217264/112893199-a3c81080-90da-11eb-82b9-11185512dd03.png)

**Comment by flipsasser** [comment]
Fixed!
