### ISSUE TITLE
Improvements to interface

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#58]
Below are some additional tweaks to improve the tool, I defer to y'all on how you'd like to break this out into the phases of development.
- [x] quick jump to ready to review to skip to bottom of page for admin
- [x] remove text controls and preview window below edit window (it's just confusing), scale of edit window default to larger. We have not used styling once since launch of coyote.

---

- [ ] enlarge image for closer looking to describe https://github.com/imgix/luminous/ http://www.jacklmoore.com/zoom/
- [ ] hide images with file path `mcachicago.org/media/` these are press images for download and not public facing
- [ ] Archive user instead of delete?
- [ ] NICE TO HAVE: On admin landing page, load more after assigning/approving

Regular users permissions are too limited change to the following or maybe these are bugs:
- [x] Regular users can see all descriptions (important for learning) (or is this a bug? https://github.com/coyote-team/coyote/issues/55 )
- [x] Regular users can describe any image even if not assigned to them (why prevent someone from describing anything?)

**Comment by alavatelliMCA** [comment]
More thoughts on this:

When an image marked priority has been described (even if partial) AND the description is approved it should not appear in the unassigned queue, right?

I will unprioritize these recently described (and approved) images, but a future improvement could be to remove the priority tag once a description has been approved.

http://coyote.mcachicago.org/images/12510

**Comment by seeReadCode** [comment]
@alavatelliMCA images appear in the unassigned queue if they have not been assigned.  Do you want me to filter and label such that the 'Unassigned' queue becomes the 'Unassigned and undescribed' queue?

**Comment by alavatelliMCA** [comment]
Yes this sounds like a more efficient workflow. Thank you!

**Comment by alavatelliMCA** [comment]
More improvements:
- [ ] enlarge image for closer looking to describe
- [ ] quick jump to ready to review to skip to bottom of page for admin

**Comment by seeReadCode** [comment]
I moved the new suggestions from the previous comment up into the main text above so they are tracked more clearly in Github.
