### ISSUE TITLE
Deleted organization names don't get cleared

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#593]
When making a new organization, it can't be named the same as an old deleted organization. This is problematic especially when resetting one on staging, etc.

**Comment by flipsasser** [comment]
Fix for this is headed to staging

**Comment by jkva** [comment]
Verified locally as current bug.  Steps to reproduce:

1) create new organization "Test Museum"
2) delete "Test Museum"
3) attempt to create new organization "Test Museum"

Result: `ActiveRecord::RecordNotUnique in OrganizationsController#create`

**Comment by jkva** [comment]
There is a [draft PR which resolves this issue](https://github.com/coyote-team/coyote/pull/649). However I am curious why deleted organizations are tracked. We also track (retain) deleted resources, but not resource representations. @sinabahram any thoughts on this?

**Comment by jkva** [comment]
This issue also relates to issue #512.

**Comment by sinabahram** [comment]
This may be worth a voice conversation, but we didn't want to lose a bunch of descriptions in case someone accidentally deleted an organization, so I'd like a way of archiving them and deleting after a period of time, but releasing the name of course.

**Comment by jkva** [comment]
A fix for this per #649 has now been deployed on staging.

**Comment by jkva** [comment]
Closing as this has now also been deployed on production.
