### ISSUE TITLE
Spreadsheet Import Resources Very Slow

### ISSUE THREAD

**Issue by NolanHill** [coyote-team/coyote#599]
This may be a staging site issue, but importing a .csv with 3 columns and 10 rows took a total of 2.5 minutes. Another .csv with 4 columns and 100 rows took around 7 minutes. Not a huge issue since this can run in the background, but wanted to note.

**Comment by NolanHill** [comment]
Update: this import has been "parsing" for many days now: https://staging.coyote.pics/organizations/65-client-test-org/imports/22

**Comment by SamuelHShaw** [comment]
Closing as this was an issue when Coyote was running on different infrstructure.
