### ISSUE TITLE
Support page (instead of email link)

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#60]
Rather than link to your email we'd love to have a page for more extensive information about describing, links to resources in addition to a link to email support.

Is this something that we would be able to edit or would you like comprehensive content? (in github is fine if that is the only way).

**Comment by seeReadCode** [comment]
Here's your page you can edit on Github:
https://github.com/coyote-team/coyote/blob/master/app/views/pages/_support.md

When you are happy with it, let me know and I'll change out the support link and deploy.

**Comment by seeReadCode** [comment]
@alavatelliMCA I noticed you've made some updates for this so I imagine you are ready to have this link switched out and the change deployed.

**Comment by alavatelliMCA** [comment]
Yes! Thank you!
