### ISSUE TITLE
Investigate if Sentry is best option for Rails Applications

### ISSUE THREAD

**Issue by Pen-a11y** [coyote-team/coyote#601]
Sentry is an SDK for ruby applications, to allow users to report messages, exceptions, and tracing events. Sentry is currently used in Coyote, but can become expensive quickly, and has only a one user limit.

We should look into other options than Sentry, and see if other options would be better for Coyote.

**Comment by Pen-a11y** [comment]
Looking at different alternatives it looks like there are a couple of options.

- Rollbar: It seems to have more features than sentry, allows for multiple users per service, but the pricing is still expensive

- GlitchTip: It is open source, and can use Sentry's open source SDK's to retrieve data so it is easier to integrate. The service is free if it is installed on your own servers, but is relatively cheap for them to host. 
The main issue with GlitchTip is that it does not have much information online, and seems to lack some features that Sentry has.

If anyone has some other services as well. Please post them here

**Comment by jkva** [comment]
@sinabahram @jscholes @Pen-a11y Sentry charges $26 a month on the team plan. GlitchTip is free up to a 1000 events per month, and above that one pays either $15 for a hosted solution or you run it yourself on Docker somewhere. Which will probably also cost $1000. 

Since we're trying to move Coyote staging to DigitalOcean, it'd seem a good step to also start pointing it to GlitchTip on a free plan, and see how it does. If we reach the limit on events, we can always switch to the $15 plan, which is cheaper than the cheapest paid plan on Sentry.

**Comment by sinabahram** [comment]
Sure thing, I'm ok with this. I can sign us up for whatever and provide credentials, etc.

Shall we proceed?

Guessing we want to just use them for free, per Job's suggestion and then decide to host ourselves or just give them their $15/month so as not to deal with it.

**Comment by jkva** [comment]
I see I said above: "GlitchTip is free up to a 1000 events per month, and above that one pays either $15 for a hosted solution or you run it yourself on Docker somewhere. Which will probably also cost $1000."

What I meant to say was: "which will probably also cost [at least] $15.".

Apart from that, yeah go ahead and sign up for an account @sinabahram. That way we've got one when we need one.

**Comment by Pen-a11y** [comment]
Great, so the next step after @sinabahram creates an account is to try and set up GlitchTip in coyote.

I'll look into configuring coyote with Glitchtip, and make sure it is working the way we would want it to. 

We could start with the free version, and if it seems we need more than 1000 events per month, then we can decide to pay $15/month for the hosted version, or host it ourselves.

**Comment by jkva** [comment]
Closing as deprecated by AppSignal integration.
