### ISSUE TITLE
Text content changes - homepage and help text

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#61]
**Homepage (before logging in)**

The open-source Coyote software was developed by the Museum of Contemporary Art Chicago to support a distributed workflow for describing images in our web CMS and publishing those descriptions to our public website. The MCA team is creating both alt-text descriptions of 20–30 words, as well as much longer descriptions, particularly of collection works.

Coyote offers role-based logins to facilitate image description tasks. Administrators approve, assign, and review descriptions. Cataloguers create descriptions from an assignment queue or select images to describe. To provide additional context for cataloguers, Coyote presents the image caption, where available. Coyote allows multiple cataloguers to describe an image; it also allows a single cataloguer to create multiple description–potentially in multiple languages–of the same image. 

More information about image description projects at the MCA and elsewhere is available at www.coyote.pics, along with contact information for the project team. You can also view or hear image descriptions on the MCA website at www.mcachicago.org. 

**Long description:**
A long description is a lengthier text than a traditional alt-text that attempts to provide a . comprehensive representation of an image. Long descriptions can range from one sentence to several paragraphs.

**Alt text:**
Alt text—or alternative text—is the text that is read to a blind user by screen reader software. Alt text describes the image’s main focus. It’s best to keep the alt text less than 20 to 30 words. If the image has a caption, try not to repeat the caption content in alt text. If the image is a graphic element such as a logo, one or two words is preferred (e.g. Home, Twitter, Contact Us).

**Comment by alavatelliMCA** [comment]
**And the footer:**

Coyote is a project of the Museum of Contemporary Art Chicago in collaboration with Prime Access Consulting. It has been generously supported by Lois and Steve Eisen.

**Comment by sinabahram** [comment]
This is great

**Comment by alavatelliMCA** [comment]
Will these changes also be made in the public instance?

**Comment by seeReadCode** [comment]
They are live at http://coyote.mcachicago.org or do you mean elsewhere?

**Comment by alavatelliMCA** [comment]
I meant for the instance that runs the bookmarklet.

**Comment by seeReadCode** [comment]
Right now it would be live on any instance.

**Comment by alavatelliMCA** [comment]
Fabulous! Thank you.

**Comment by seeReadCode** [comment]
@alavatelliMCA might we add a link to this repo in the homepage text, in the footer, or both?

**Comment by alavatelliMCA** [comment]
We are just going to put it on Coyote.pics the project information website that is linked to from the homepage, what is the link I should use?

**Comment by seeReadCode** [comment]
https://github.com/coyote-team/coyote
