### ISSUE TITLE
Investigate possible memory leak on staging

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#632]
![A 7 day graph of memory usages, showing a slow increase from 60% to 80%](https://user-images.githubusercontent.com/217264/161992665-923c1797-a2f5-472f-9381-3eae31b58053.png)

It seems the amount of memory usage for coyote staging slowly increases. This suggests perhaps a memory leak or garbage collection not being able to free used pages.

**Comment by jkva** [comment]
Might be worthwhile to switch staging to `jemalloc` and see how it performs.
https://medium.com/code-wild/how-jemalloc-improved-memory-usage-of-our-rails-application-7038d5926d4

**Comment by sinabahram** [comment]
This seems like a good idea and reasonably easy to implement/test

**Comment by jkva** [comment]
Upgrading the Ruby base image to 2.7.5 (#636) seems to have addressed the memory leak issue, since memory usage is now stable at 59% across 3 days.

Given the problems AppSignal caused when manually triggering a major GC sweep, and the suspicious memory problems after the started usage of the AppSignal agent, leads me to believe that the Ruby 2.6.6. image in combination with the AppSignal agent was causing the memory leak to begin with.
