### ISSUE TITLE
Sorting configuration does not retain chosen setting

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#645]
When sorting resources, the first time a custom sort order is picked, this option is not correctly set. For instance, when choosing "Date imported, recent", the picked setting becomes "Date imported, oldest". The user is required to choose the custom sort order once more for it to take.

**Comment by jacobyarborough** [comment]
Fixed and closed by [PR 651](https://github.com/coyote-team/coyote/pull/651)
