### ISSUE TITLE
Representation updates send incorrect payload to webhook

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#659]
In the scenario of having two representations for a resource — 1 and 2 — , and updating representation 2, representation 1 will get posted to the resource group's callback url. This should always be the representation that actually got modified.

This is related to the way `JSONAPI::Serializable::Renderer` handles `SerializableResource` and `SerializableRepresentation`.

**Comment by jacobyarborough** [comment]
## Solution Found:

If there are two existing descriptions of the same metum type (alt or long) where at least one is approved for a single resource, a webhook triggered by an update to either description will only return the highest ordered description (highest being 1). Each description has an order field that can be set upon creation or editing. If no order is set upon creating a description, the order will be assigned automatically. Whichever description has the order of 1 for any set of approved descriptions of the same metum type for a given resource will be returned in the webhook no matter which of the two approved descriptions is updated.

### Example of a description having an order not equal to 1
<img width="1411" alt="Screenshot of an existing description. The order field is bordered by a red box showing a value of 2. The message on the screenshot says to set the current order to 1 for it to be returned in the webhook. The edit button is highlighted by a red border." src="https://github.com/coyote-team/coyote/assets/86209646/ac2447f5-8bf6-4c8f-b2f0-47b9618d3d06">

### Steps to set or edit the order for a description:

#### To set the order upon creation:
1. Once on the new description creation page click "additional details"
2. Scroll down to the "Order" field and set the value to 1
<img width="1400" alt="Screenshot of the creation page for a description. The order field input is highlighted by a red box with a value set to 1. The message on the screenshot says 'change the order field to have a value of 1' with an arrow pointing to the highlighted field." src="https://github.com/coyote-team/coyote/assets/86209646/0f43dd31-ca6a-4e26-a78c-bfdf7dcc33c7">
&nbsp;&nbsp;&nbsp;&nbsp;3. Click "Create Description" as normal

#### To edit the order once the description is created:
1. Click on an existing description
2. click "Edit"
3. Once on the description edit page click "additional details"
5. scroll down to the "Order" field and replace the value with 1
<img width="1396" alt="Screenshot of the edit description page. The order field is highlighted by a red box with a blank value. A message says 'Enter a value of 1 for the Order field when creating a new description when another approved description of the same type exists.'. There is an arrow pointing from the message to the highlighted field." src="https://github.com/coyote-team/coyote/assets/86209646/c78cd3f6-31cc-4823-8263-0a495fd268d8">
&nbsp;&nbsp;&nbsp;&nbsp;6. click "Update Description" as normal
