### ISSUE TITLE
Assigned images not appearing in the user's queue

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#66]
When Matti Allison is logged in despite my having assigned her images no images appear in her Queue.

**Comment by seeReadCode** [comment]
I just tested assignment and it seemed to work.  Could you provide any more details?  Is this issue still occurring?

**Comment by alavatelliMCA** [comment]
Duplicate accounts, I didn't realize she created two. Future feature: merge accounts? 

What happens the the descriptions of a user if they are "deleted" can we have an Archive user instead?

**Comment by seeReadCode** [comment]
I've done the merges by hand thus far (only one or two occasions if I remember correctly) but you should be able to do this without too much issue. 

Here's how:

1. Change the name of the old user to clarify things.
2. From that user's pages, open the edit link to each of their images and set the the author to the correct user record and save.
3. Delete the old user record.

If an author is deleted, their descriptions are orphaned.

I'll re-open this issue and then please let me know if this works (and close this item again if it does).
