### ISSUE TITLE
Resource name source_uri FK constraint should not apply when resource is deleted

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#664]

**Comment by jkva** [comment]
When deleted, the `is_deleted` column for a resource is set to `true`. This still allows for the resource to be viewed (this is the bug) although it does not show up in the resource overview or statistics.

It does relate to #661 since the duplicate `source_uri` for the identical organisation triggers a key constraint.

```
PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_resources_on_source_uri_and_organization_id" DETAIL: Key (source_uri, organization_id)=(https://coyote.pics/wp-content/uploads/2016/02/Screen-Shot-2016-02-29-at-10.05.14-AM-1024x683.png, 1) already exists.
```

**Comment by jkva** [comment]
@sinabahram what is the rationale for soft-deleting resources via the toggling of the `is_deleted` property? Recovery in case of accidental removal?

The easiest solution would be to modify the triggering index into a conditional index such that the duplicate organisation+source_uri violation only hits for non-deleted resources.

**Comment by sinabahram** [comment]
Yes, that's correct. Want the ability for them to hang around for 30 to 60 days (it's not that much of a hit, and we can hard delete later), so however we achieve that is good with me such that the old name can be reused.

If someone decides to undelete an org, by which I mean Staff, then all that needs to happen is the name check can occur then. It can say, go delete the org having this name before you can undelete this one.

Problem solved.

Thanks so much
