### ISSUE TITLE
Filter search failure

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#67]
when multiple elements are selected in filtering no results appear. The text appearing under the blank list show a search is `art "1" kjm "1"`
<img width="1424" alt="screen shot 2016-12-22 at 12 17 58 pm" src="https://cloud.githubusercontent.com/assets/8040710/21435770/2271dba8-c841-11e6-858b-806613c77a90.png">

If only one of the filtering items is used only `priority` or only `unassigned` it works ok

**Comment by alavatelliMCA** [comment]
More on this, we figured out that descriptions that are Partially Completed and Ready to Review only show up in Partially Completed. So when searching Partially Completed and Priority we see the ones that are missing, but we also see the approved descriptions.

This issue is for administrators who are trying to search for descriptions that need review in this list window. So some admins aren't using the home window ready to review section, especially on approval sprints which we are having right now.

**Comment by seeReadCode** [comment]
@alavatelliMCA I'm seeing a slightly different issue.

Here are Priority images that are Ready to Review:

![screen shot 2017-03-15 at 6 08 09 pm](https://cloud.githubusercontent.com/assets/8710696/23972984/7b8b675e-09aa-11e7-8550-5bb0d841c14c.png)

Here are Priority images that are Partially Completed:

![screen shot 2017-03-15 at 6 08 09 pm](https://cloud.githubusercontent.com/assets/8710696/23973054/c0d49a10-09aa-11e7-91d7-b808b013c5bb.png)

I think there's an underlying issue where the status of an image is being marked incorrectly. c.f. http://coyote.mcachicago.org/images/13164

**Comment by seeReadCode** [comment]
Testing with <http://localhost:3000/images/9361>...

```
count = 0
Image.where(status_code: 1).each do |i|
status_code = i.status_code
i.update_status
if i.status_code != status_code
i.save
count ++
end
puts count
end
```

**Comment by seeReadCode** [comment]
Ok, this should be fixed now
