### ISSUE TITLE
Updating context over time

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#69]
Coyote needs to sync on context-
http://coyote.mcachicago.org/images/11666 shows an image with a context at http://admin.mcachicago.org/Support/Membership which is an outdated subdomain, but also no longer displays that image. Let me know what support you would need from Tomas on resolving this this.

screenshot of http://coyote.mcachicago.org/images/11666 :
<img width="1422" alt="screen shot 2016-12-22 at 12 53 40 pm" src="https://cloud.githubusercontent.com/assets/8040710/21436866/35fd9482-c846-11e6-8a7a-449c7043a768.png">

screenshot of http://admin.mcachicago.org/Support/Membership :
<img width="1416" alt="screen shot 2016-12-22 at 12 53 50 pm" src="https://cloud.githubusercontent.com/assets/8040710/21436865/35fd3b54-c846-11e6-9e39-8d621d2bb2e2.png">

**Comment by seeReadCode** [comment]
When an image changes context on the CMS, Tomas needs to send a PUT to the appropriate image with the new `page_urls` value, see http://coyote.mcachicago.org/apipie/1.0/images/update.html

**Comment by alavatelliMCA** [comment]
Not sure if this is resolved in new coyote, but we'll be sure soon.
