### ISSUE TITLE
Create New Backup Process for Coyote Rails App Database

### ISSUE THREAD

**Issue by SamuelHShaw** [coyote-team/coyote#690]
This is a task to create a new process to back up the Coyote Rails app database. 

To start, we need to research and evaluate the following options:
1. The best modern accepted practice to back up a Rails app database. 
2. An implementation similar to what we do for [PAC.bz](http://pac.bz/) i.e. write cron job, dump db, and put it into cloud.
3. Snap Shooter - They have a free plan we may be able to use. FYI there may be an issue because we run our DB in a container and they may not expect that
4. Sidekick

**Comment by jscholes** [comment]
@SamuelHShaw Can we please move this to pac-ops, and delete this issue?  It's a private/internal task that, for now at least, relates to our hosting of Coyote, rather than the open-source product as a whole.

**Comment by SamuelHShaw** [comment]
Closing this issue as it has been recreated in pac-ops.
