### ISSUE TITLE
Resolving duplicates

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#70]
We have many duplicates from before we had a central asset repository, there is a workaround–copy-pasting from one to the next, and perhaps beings that it is rare for a website not to have a central asset repository this is something we should stick to resolving on our own. But wanted to flag and note this potential feature, as we would want coyote to get cleaned up once we fix our duplicates on the website end, kind of relates to the updating of context #69

**Comment by seeReadCode** [comment]
Also relates to #74
