### ISSUE TITLE
Users do not appear in any particular order in dropdown lists

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#71]
On images list page the users are in no particular order:

Assign to
![screen shot 2017-01-17 at 6 25 21 pm](https://cloud.githubusercontent.com/assets/8040710/22082817/f64bc9d6-dd8e-11e6-846a-e94b3f95fed2.png)

and assigned to filter
![screen shot 2017-01-17 at 6 29 43 pm](https://cloud.githubusercontent.com/assets/8040710/22082806/ec106b98-dd8e-11e6-9136-b0c8f1336fa8.png)

**Comment by seeReadCode** [comment]
Correct me if I'm wrong @alavatelliMCA but users are alphabetized by last name in the 'Assign To' dropdown, no?  There might be some glitches based on how the names are inputted.  I see on the filter that they have not been sorted though.

**Comment by alavatelliMCA** [comment]
True. In the "Assign to" they are alphabetized by last name, as they are on the users list view. However, in the filter dropdown they are not sorted.
