### ISSUE TITLE
User accounts getting mixed up in audit log

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#72]
Yesterday Sheila and I were working on descriptions together, we were the only two users involved in the editing and approving process. However now two other names are appearing in place of my own. 
http://coyote.mcachicago.org/descriptions/4787 
![screen shot 2017-01-19 at 10 45 54 am](https://cloud.githubusercontent.com/assets/8040710/22118242/9ef5cb74-de3c-11e6-81c5-abc3d86c1590.png)

Sheila was the original author, I edited, and not sure which of us made the final approval.

There is also this page doing something similar:
http://coyote.mcachicago.org/descriptions/3734 was also authored by Sheila if I recall correctly, for all of these it was only Sheila and Anna (me) working on them.

Will keep my eyes peeled for others.

**Comment by seeReadCode** [comment]
I'll see if I can replicate this.

**Comment by subelsky** [comment]
hi @alavatelliMCA have you seen this again? If not is it OK to close it? We can always re-open.

**Comment by alavatelliMCA** [comment]
It's hard to identify exactly where the mixups occur, the example I provided was the one where we caught it right after it happened. We'll track down some more examples, we've continued to see this behavior on occasion.

**Comment by sinabahram** [comment]
@flipsasser  please confirm this is fixed, and then close this out.

**Comment by flipsasser** [comment]
This appears to not be an issue (I cannot replicate) so I'm going to close but we can re-open if it reoccurs
