### ISSUE TITLE
sort by date on descriptions

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#73]
This would help with troubleshooting, we are trying to target issue with description sync issues with the website and being able to sort by date would enable me to hone in on the issue.

http://coyote.mcachicago.org/descriptions

**Comment by seeReadCode** [comment]
@alavatelliMCA which date are you thinking of?  The "created at" date or the "updated at" date?

**Comment by alavatelliMCA** [comment]
I think for reviewing it is useful to look at "created at" date 

For troubleshooting sync it would be the "approved at" date.

This is lower priority in the grand scheme of enhancements.

**Comment by somedayrainbows** [comment]
@subelsky please assign to me, thank you!

**Comment by sinabahram** [comment]
@flipsasser  is this already possible/implemented in current system? If not, let's discuss. If so, please close this out.

**Comment by flipsasser** [comment]
This is implemented ....... now :)
