### ISSUE TITLE
Archiving images that have been removed or duplicated from the site

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#74]
We have some images that have been removed from the website but may be hiding in the central asset repository that should be archived or something in the coyote interface. This is an example where we were having a display error on an image due to CMYK settings so we reuploaded a couple times to fix it, but only the last one is correct. You can see in the context field they all point to the same page, but in fact that page only displays the final image on this list.

http://coyote.mcachicago.org/images/13065
![screencapture-coyote-mcachicago-org-images-13065-1488566562975](https://cloud.githubusercontent.com/assets/8040710/23564956/5c262428-0011-11e7-8f49-cf35bb04bcf5.png)

http://coyote.mcachicago.org/images/13064
![screencapture-coyote-mcachicago-org-images-13064-1488566580777](https://cloud.githubusercontent.com/assets/8040710/23564955/5c25ba1a-0011-11e7-9bc2-8ad5ee3fa180.png)

http://coyote.mcachicago.org/images/13066
![screencapture-coyote-mcachicago-org-images-13066-1488566548340](https://cloud.githubusercontent.com/assets/8040710/23564954/5c256dc6-0011-11e7-9622-3227ac123f7b.png)

**Comment by seeReadCode** [comment]
@sinabahram simplest approach would be that we could add a new boolean for ignore, add it to the form and show view, and then modify the scopes.

**Comment by sinabahram** [comment]
Agreed. The real question here is whether or not this deserves state e.g. “deleted” as opposed to “ignore”?

**Comment by seeReadCode** [comment]
I'd say let's use `delete` with audited record.  This will take a bit of testing to make sure the scoping all works out correctly but I think it'll be a bit cleaner in the long wrong.

**Comment by sinabahram** [comment]
Agreed.

**Comment by subelsky** [comment]
per @sinabahram this would involve finding a good reverse-image search API (part of the cron job I mentioned in #83 )

**Comment by subelsky** [comment]
We are going to pursue a solution to this issue in #96 , closing this issue for clarity
