### ISSUE TITLE
Footer on Coyote

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#76]
@sinabahram it appears you have added a link to the bookmarklet to Coyote's footer. We are concerned that our staff might use this not realizing it is a totally separate tool that will not populate our website with descriptions.

The text:
Add this Coyote bookmarklet to your bookmarks and click it to add more images, describe them, and render their annotations 
Warning: this feature is in development

It contains grammatical errors and is misleading. If you are opposed to removing this, we'll provide updated language that more clearly indicates what this link is. I think we should add the bookmarklet to Coyote.pics instead.

Thanks!
A

**Comment by sinabahram** [comment]
Sorry, that push was supposed to only be for the coyote.pics instance. Furthermore, I agree RE grammatical mistakes, etc.

 

Another thing on the todo list should be to prioritize easy content changes like this so that they do not necessitate a code push.

 

Let’s also discuss further by voice.
