### ISSUE TITLE
Publish to function

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#81]
Need a function for selecting what descriptions are published where when there are multiple approved descriptions.

e.g. 
Publish to web 
Publish to digital map

**Comment by alavatelliMCA** [comment]
For publishing feature:
I want to publish different descriptions of the same image to different contexts

e.g. Image appears on collection page and also in a blog post, I want a different description for each context.

**Comment by sinabahram** [comment]
This is a built-in feature of Coyote. Nothing is needed to be developed here, however, the blog needs to request the blog context and the website the main site context and a sales page a sales page context, etc.

**Comment by subelsky** [comment]
per @sinabahram this may be solved with enhanced documentation that clearly spells out what metadata attributes really mean as the project has evolved - metum, context, etc.

**Comment by susanchun** [comment]
Welcome @subelsky. Team: I think that we're all talking about different things here. Anna is asking about how we privilege one of multiple descriptions for publication. Sina is talking about better developing our context definitions. And Mike is correct, we need a data dictionary. Let's plan an all-dev Coyote call some time soon to work through open issues and prioritize and schedule them.
