### ISSUE TITLE
Broken images - and out of date image context links

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#83]
There are some broken images showing up in the collection group. Some have no context, some do. Image appears as broken: http://coyote.mcachicago.org/images/8785
But there is an image on the page for context: http://admin.mcachicago.org/Collection/Items/Rafael-Ferrer-Bituki-Bakilin-Bin-Bin-1974

Also, the URL is old on the collection images, they show admin.mcachicago.org as the context. Maybe the content for this group is not refreshing? 

I am troubleshooting why caption information is not displaying on the website side.

**Comment by seeReadCode** [comment]
This may not well be a coyote issue but an MCA site issue.

This is the image that is in that record (but doesn't exist).
https://mcachicago.org/api/v1/attachment_images/thumbs/56b6063fa6ad051fd60003b6.jpg

Please follow up with Tomas and feel free to loop me in on an email.

**Comment by seeReadCode** [comment]
Here's another record for that image.
http://coyote.mcachicago.org/images/12870

**Comment by seeReadCode** [comment]
See also https://github.com/coyote-team/coyote/issues/50

**Comment by subelsky** [comment]
Per @sinabahram a first, helpful idea would be to flag images that seem to be available.  We could have a cron job periodically checking for 404s. 

Another idea would be to attempt to fallback to Internet Archive.

**Comment by subelsky** [comment]
We are going to pursue a solution to this issue in #96 , closing this issue for clarity
