### ISSUE TITLE
Additional enhancements

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#89]
User feedback on the admin side, low priority.

- I want to find descriptions approved by a particular user
- Assignments list view not usable http://coyote.mcachicago.org/assignments, needs to include thumbnail and description status, and useful to know if priority
- Admin should be able to adjust user settings. e.g. create admin users or change admin users to standard users.
- Users list, date of last login and/or date of last description – ability to archive users rather than delete
- Drop down to select author, names appear in no particular order, should be alpha

General user functions
- Word count on text entry window
- Description page is easily confused with Image page, http://coyote.mcachicago.org/descriptions/5008 for instance in the header showing the image's status tag dominates over the description status which is approved. Maybe the image status tags only show on the image page?

**Comment by sinabahram** [comment]
New UI/UX work will uncover some of these if they still exist in current system, and then lets get individual tickets to handle them.
