### ISSUE TITLE
Title should not be an editable field

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#94]
Title is imported from the website with the image, but is an editable field in coyote posing sync conflicts.

Please update Title to be non-editable.

**Comment by subelsky** [comment]
@alavatelliMCA This change means you can't change the title on images that have already been loaded into the database. It will show up in the software next time we deploy. I didn't get into that with @sinabahram yet. Ideally I would like to build a staging server on Heroku where we could test out changes like this

**Comment by sinabahram** [comment]
Happy to use live.coyote.pics for staging as well.

**Comment by subelsky** [comment]
@sinabahram in that case let me know how to deploy there & I'll try it out

**Comment by sinabahram** [comment]
Instead of using the old deploy system, let’s spin up another one and transition it over.

 

Voice coms will help figure this plan out.
